In [1]:
#install.packages("baseballr")
#install.packages("dplyr")
#install.packages("readr")
#install.packages("lubridate")
#install.packages("tidyverse")
#install.packages("duckdb")
install.packages("purrr")
library(purrr)
library(duckdb)
library(tidyverse)
library(baseballr)
library(dplyr)
library(readr)
library(lubridate)

The downloaded binary packages are in
	/var/folders/4k/3pfkn1jn039bp8wy8410pn3m0000gn/T//RtmpA4ULcv/downloaded_packages

Loading required package: DBI

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.2     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

## WHEN READING THIS FILE, KEEP IN MIND THAT THESE ARE INCREMENTAL STEPS ALONG THE DATA LOADING PROCESS THAT IS PRIMARILY CONDUCTED IN project.ipynb. THIS IS NOT INTENDED TO BE ONE STRAIGHT WORKFLOW

In [2]:
GBS <- read_csv("/Users/owendrummond/Documents/python_projects/Capstone/GameBoxScores_PostBullpen.csv")

Rows: 17906 Columns: 245
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (72): DayOfWeek, AwayTeam, AwayLeague, HomeTeam, HomeLeague, Day/Night...
dbl  (172): GAMEID, Unnamed: 0, AwayGameNum, HomeGameNum, AwayScore, HomeSco...
date   (1): Date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [3]:
GBSHitting <- read_csv("/Users/owendrummond/Documents/python_projects/Capstone/GBSHitting.csv")

Rows: 17906 Columns: 829
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr   (72): DayOfWeek, AwayTeam, AwayLeague, HomeTeam, HomeLeague, Day/Night...
dbl  (756): GAMEID, Unnamed: 0, AwayGameNum, HomeGameNum, AwayScore, HomeSco...
date   (1): Date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [137]:
# Unique pitcher season and ID combinations to be used in game log data gathering process.

unique_pitcher_seasons <- GBS %>%
  select(Year, HomePitcherIDFG, AwayPitcherIDFG) %>%
  pivot_longer(
    cols = c(HomePitcherIDFG, AwayPitcherIDFG), 
    names_to = "Side", 
    values_to = "PitcherID"
  ) %>%
  # Keep only one row per Pitcher/Season
  distinct(PitcherID, Year)

# View the result
print(unique_pitcher_seasons)

# A tibble: 2,890 × 2
   PitcherID  Year
       <dbl> <dbl>
 1      8782  2019
 2     10603  2019
 3     19427  2019
 4     16400  2019
 5     15440  2019
 6     10190  2019
 7      5401  2019
 8     14527  2019
 9      4676  2019
10     11486  2019
# ℹ 2,880 more rows

In [4]:
write_csv(unique_pitcher_seasons, "unique_pitcher_seasons.csv")

ERROR: Error: object 'unique_pitcher_seasons' not found

In [13]:
unique_pitcher_seasons_temp <- read_csv('/Users/owendrummond/Documents/python_projects/Capstone/unique_pitcher_seasons.csv')
player_dim <- read_csv('/Users/owendrummond/Documents/python_projects/Capstone/player_dim_live.csv')

Rows: 2890 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): PitcherID, Year

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 2522 Columns: 6
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (5): player_name, retro_id, bref_id, fg_id, Team
dbl (1): mlb_id

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [14]:
unique_pitcher_seasons_2026 <- unique_pitcher_seasons_temp %>%
  filter(Year >= 2023) %>%
  select(PitcherID) %>%
  distinct() %>%
  mutate(
    PitcherID = as.character(PitcherID),
    Year = 2026
  )

# 2. Get fg_id, ensure it is character, and rename
new_pitcher_ids <- player_dim %>%
  filter(is.na(retro_id) | retro_id == "") %>%
  select(PitcherID = fg_id) %>%
  mutate(
    PitcherID = as.character(PitcherID),
    Year = 2026
  )

In [17]:
unique_pitcher_seasons_2026 <- bind_rows(unique_pitcher_seasons_2026, new_pitcher_ids)

In [18]:
fg_pitcher_game_logs(playerid = unique_pitcher_seasons_2026$PitcherID[1],year = unique_pitcher_seasons_2026$Year[1])

  PlayerName    playerid Date       Opp  teamid season Team HomeAway Age W ⋯
1 Cal Quantrill 19312    2026-04-18 @SEA 13     2026   TEX  A        31  0 ⋯
2 Cal Quantrill 19312    2026-04-16 @ATH 13     2026   TEX  A        31  1 ⋯
  Events EV       LA       Barrels Barrel%   maxEV HardHit HardHit%  gamedate
1 6      99.63333 26.00000 2       0.3333333 106.7 4       0.6666667 2026-04-18
2 3      84.90000 18.33333 0       0.0000000 103.7 1       0.3333333 2026-04-16
  dh
1 0
2 0

In [144]:
fg_pitcher_game_logs(playerid = 8782,year = 2019)

Request failed [403]. Retrying in 1 seconds...

Request failed [403]. Retrying in 3 seconds...

2026-04-14 22:34:38.922271: Invalid arguments or no pitcher game log data available!

ERROR: Error in fg_pitcher_game_logs(playerid = 8782, year = 2019): object 'payload' not found

## OG Pitcher Run (Does not include 2026)

#### Avoid running on your own, this will take multiple hours

In [151]:
# Because this function was taking so long to execute, and because I was continually getting thrown HTTP request blockers, I had some some A.I. enhancements
# to avoid these blockages such as error detection and periodic sleeps. The idea for the function however, was my own.

checkpoint_file <- "master_logs_checkpoint.rds"

if (file.exists(checkpoint_file)) {
  all_logs_list <- readRDS(checkpoint_file)
  # Identify which ID/Year combos we already have
  completed <- bind_rows(all_logs_list) %>%
    distinct(PitcherID, Year)
  
  # Filter our queue to only include those NOT in the completed list
  queue <- unique_pitcher_seasons %>%
    anti_join(completed, by = c("PitcherID" = "PitcherID", "Year" = "Year"))
  
  message(paste("Resuming... skipping", nrow(completed), "already downloaded combos."))
} else {
  all_logs_list <- list()
  queue <- unique_pitcher_seasons
}

# THE LOOP
for(i in 1:nrow(queue)) {
  p_id <- queue$PitcherID[i]
  p_year <- queue$Year[i]
  
  message(paste0("Processing (", i, "/", nrow(queue), "): ID ", p_id, " Year ", p_year))
  
  # Try to get the log
  log <- tryCatch({
    fg_pitcher_game_logs(playerid = p_id, year = p_year)
  }, error = function(e) {
    if (grepl("403", e$message) || grepl("payload", e$message)) {
      message("!!! API Blocker/403 detected. Sleeping for 2 minutes to cool down...")
      Sys.sleep(120) 
      return(NULL)
    }
    return(NULL)
  })
  
  # DATA VALIDATION & SAVING
  if(!is.null(log) && nrow(log) > 0) {
    log$PitcherID <- p_id
    log$Year <- p_year
    all_logs_list[[length(all_logs_list) + 1]] <- log
  }
  
  # Save a checkpoint every 10 pitchers so you don't lose work
  if (i %% 10 == 0) {
    saveRDS(all_logs_list, checkpoint_file)
    message("--- Checkpoint saved.")
  }
  
  # VARIABLE SLEEP
  # Random sleep between 1.5 and 3.5 seconds to avoid detection
  Sys.sleep(runif(1, 1.5, 3.5))
}

master_pitcher_logs <- bind_rows(all_logs_list)
saveRDS(master_pitcher_logs, "master_pitcher_logs_final.rds")
message("Process Complete! All logs saved to master_pitcher_logs_final.rds")

Processing (1/2890): ID 8782 Year 2019

Processing (2/2890): ID 10603 Year 2019

Processing (3/2890): ID 19427 Year 2019

Processing (4/2890): ID 16400 Year 2019

Processing (5/2890): ID 15440 Year 2019

Processing (6/2890): ID 10190 Year 2019

Processing (7/2890): ID 5401 Year 2019

Processing (8/2890): ID 14527 Year 2019

Processing (9/2890): ID 4676 Year 2019

Processing (10/2890): ID 11486 Year 2019

--- Checkpoint saved.

Processing (11/2890): ID 16918 Year 2019

Processing (12/2890): ID 18383 Year 2019

Processing (13/2890): ID 13074 Year 2019

Processing (14/2890): ID 19309 Year 2019

Processing (15/2890): ID 4806 Year 2019

Processing (16/2890): ID 9323 Year 2019

Processing (17/2890): ID 14078 Year 2019

Processing (18/2890): ID 12970 Year 2019

Processing (19/2890): ID 12699 Year 2019

Processing (20/2890): ID 14288 Year 2019

--- Checkpoint saved.

Processing (21/2890): ID 8779 Year 2019

Processing (22/2890): ID 10021 Year 2019

Processing (23/2890): ID 7410 Year 2019

Processing (24/2890): ID 10130 Year 2019

Processing (25/2890): ID 1943 Year 2019

Processing (26/2890): ID 6797 Year 2019

Processing (27/2890): ID 11423 Year 2019

Processing (28/2890): ID 7448 Year 2019

Processing (29/2890): ID 15038 Year 2019

Processing (30/2890): ID 19316 Year 2019

--- Checkpoint saved.

Processing (31/2890): ID 18498 Year 2019

Processing (32/2890): ID 3284 Year 2019

Processing (33/2890): ID 10310 Year 2019

Processing (34/2890): ID 17085 Year 2019

Processing (35/2890): ID 2233 Year 2019

Processing (36/2890): ID 16977 Year 2019

Processing (37/2890): ID 9460 Year 2019

Processing (38/2890): ID 6249 Year 2019

Processing (39/2890): ID 8700 Year 2019

Processing (40/2890): ID 2520 Year 2019

--- Checkpoint saved.

Processing (41/2890): ID 8362 Year 2019

Processing (42/2890): ID 4153 Year 2019

Processing (43/2890): ID 6397 Year 2019

Processing (44/2890): ID 7872 Year 2019

Processing (45/2890): ID 14374 Year 2019

Processing (46/2890): ID 17149 Year 2019

Processing (47/2890): ID 7146 Year 2019

Processing (48/2890): ID 14825 Year 2019

Processing (49/2890): ID 4972 Year 2019

Processing (50/2890): ID 13183 Year 2019

--- Checkpoint saved.

Processing (51/2890): ID 14916 Year 2019

Processing (52/2890): ID 19320 Year 2019

Processing (53/2890): ID 19374 Year 2019

Processing (54/2890): ID 3137 Year 2019

Processing (55/2890): ID 9803 Year 2019

Processing (56/2890): ID 7593 Year 2019

Processing (57/2890): ID 12917 Year 2019

Processing (58/2890): ID 11713 Year 2019

Processing (59/2890): ID 13125 Year 2019

Processing (60/2890): ID 5448 Year 2019

--- Checkpoint saved.

Processing (61/2890): ID 15734 Year 2019

Processing (62/2890): ID 13774 Year 2019

Processing (63/2890): ID 3548 Year 2019

Processing (64/2890): ID 12703 Year 2019

Processing (65/2890): ID 15947 Year 2019

Processing (66/2890): ID 404 Year 2019

Processing (67/2890): ID 13431 Year 2019

Processing (68/2890): ID 1994 Year 2019

Processing (69/2890): ID 14862 Year 2019

Processing (70/2890): ID 13743 Year 2019

--- Checkpoint saved.

Processing (71/2890): ID 4930 Year 2019

Processing (72/2890): ID 2608 Year 2019

Processing (73/2890): ID 14444 Year 2019

Processing (74/2890): ID 10131 Year 2019

Processing (75/2890): ID 19206 Year 2019

Processing (76/2890): ID 15291 Year 2019

Processing (77/2890): ID 6902 Year 2019

Processing (78/2890): ID 13475 Year 2019

Processing (79/2890): ID 16980 Year 2019

Processing (80/2890): ID 17018 Year 2019

--- Checkpoint saved.

Processing (81/2890): ID 11490 Year 2019

Processing (82/2890): ID 15474 Year 2019

Processing (83/2890): ID 11694 Year 2019

Processing (84/2890): ID 16149 Year 2019

Processing (85/2890): ID 18679 Year 2019

Processing (86/2890): ID 14168 Year 2019

Processing (87/2890): ID 10811 Year 2019

Processing (88/2890): ID 17479 Year 2019

Processing (89/2890): ID 4371 Year 2019

Processing (90/2890): ID 11762 Year 2019

--- Checkpoint saved.

Processing (91/2890): ID 16256 Year 2019

Processing (92/2890): ID 10123 Year 2019

Processing (93/2890): ID 13360 Year 2019

Processing (94/2890): ID 8223 Year 2019

Processing (95/2890): ID 6345 Year 2019

Processing (96/2890): ID 5257 Year 2019

Processing (97/2890): ID 13164 Year 2019

Processing (98/2890): ID 16130 Year 2019

Processing (99/2890): ID 16207 Year 2019

Processing (100/2890): ID 12304 Year 2019

--- Checkpoint saved.

Processing (101/2890): ID 2717 Year 2019

Processing (102/2890): ID 14309 Year 2019

Processing (103/2890): ID 15467 Year 2019

Processing (104/2890): ID 14524 Year 2019

Processing (105/2890): ID 5524 Year 2019

Processing (106/2890): ID 15764 Year 2019

Processing (107/2890): ID 13543 Year 2019

Processing (108/2890): ID 5221 Year 2019

Processing (109/2890): ID 17030 Year 2019

Processing (110/2890): ID 18684 Year 2019

--- Checkpoint saved.

Processing (111/2890): ID 12664 Year 2019

Processing (112/2890): ID 12049 Year 2019

Processing (113/2890): ID 15552 Year 2019

Processing (114/2890): ID 17536 Year 2019

Processing (115/2890): ID 1841 Year 2019

Processing (116/2890): ID 3184 Year 2019

Processing (117/2890): ID 17425 Year 2019

Processing (118/2890): ID 13799 Year 2019

Processing (119/2890): ID 15091 Year 2019

Processing (120/2890): ID 2036 Year 2019

--- Checkpoint saved.

Processing (121/2890): ID 10954 Year 2019

Processing (122/2890): ID 13361 Year 2019

Processing (123/2890): ID 3551 Year 2019

Processing (124/2890): ID 10160 Year 2019

Processing (125/2890): ID 8044 Year 2019

Processing (126/2890): ID 6632 Year 2019

Processing (127/2890): ID 16162 Year 2019

Processing (128/2890): ID 16401 Year 2019

Processing (129/2890): ID 15454 Year 2019

Processing (130/2890): ID 16269 Year 2019

--- Checkpoint saved.

Processing (131/2890): ID 7754 Year 2019

Processing (132/2890): ID 8753 Year 2019

Processing (133/2890): ID 5358 Year 2019

Processing (134/2890): ID 7608 Year 2019

Processing (135/2890): ID 15423 Year 2019

Processing (136/2890): ID 12768 Year 2019

Processing (137/2890): ID 15488 Year 2019

Processing (138/2890): ID 16502 Year 2019

Processing (139/2890): ID 13339 Year 2019

Processing (140/2890): ID 17432 Year 2019

--- Checkpoint saved.

Processing (141/2890): ID 6895 Year 2019

Processing (142/2890): ID 15200 Year 2019

Processing (143/2890): ID 16981 Year 2019

Processing (144/2890): ID 14107 Year 2019

Processing (145/2890): ID 6941 Year 2019

Processing (146/2890): ID 5640 Year 2019

Processing (147/2890): ID 13619 Year 2019

Processing (148/2890): ID 14875 Year 2019

Processing (149/2890): ID 13050 Year 2019

Processing (150/2890): ID 3542 Year 2019

--- Checkpoint saved.

Processing (151/2890): ID 13801 Year 2019

Processing (152/2890): ID 11589 Year 2019

Processing (153/2890): ID 16358 Year 2019

Processing (154/2890): ID 11426 Year 2019

Processing (155/2890): ID 3254 Year 2019

Processing (156/2890): ID 15846 Year 2019

Processing (157/2890): ID 14814 Year 2019

Processing (158/2890): ID 17295 Year 2019

Processing (159/2890): ID 14682 Year 2019

Processing (160/2890): ID 16017 Year 2019

--- Checkpoint saved.

Processing (161/2890): ID 18029 Year 2019

Processing (162/2890): ID 16933 Year 2019

Processing (163/2890): ID 15689 Year 2019

Processing (164/2890): ID 11828 Year 2019

Processing (165/2890): ID 13133 Year 2019

Processing (166/2890): ID 19256 Year 2019

Processing (167/2890): ID 16942 Year 2019

Processing (168/2890): ID 16943 Year 2019

Processing (169/2890): ID 11189 Year 2019

Processing (170/2890): ID 12918 Year 2019

--- Checkpoint saved.

Processing (171/2890): ID 14272 Year 2019

Processing (172/2890): ID 12808 Year 2019

Processing (173/2890): ID 4505 Year 2019

Processing (174/2890): ID 15157 Year 2019

Processing (175/2890): ID 4338 Year 2019

Processing (176/2890): ID 13804 Year 2019

Processing (177/2890): ID 14765 Year 2019

Processing (178/2890): ID 9434 Year 2019

Processing (179/2890): ID 12828 Year 2019

Processing (180/2890): ID 12781 Year 2019

--- Checkpoint saved.

Processing (181/2890): ID 12800 Year 2019

Processing (182/2890): ID 15047 Year 2019

Processing (183/2890): ID 13273 Year 2019

Processing (184/2890): ID 18356 Year 2019

Processing (185/2890): ID 19990 Year 2019

Processing (186/2890): ID 15859 Year 2019

Processing (187/2890): ID 12718 Year 2019

Processing (188/2890): ID 19341 Year 2019

Processing (189/2890): ID 16110 Year 2019

Processing (190/2890): ID 2391 Year 2019

--- Checkpoint saved.

Processing (191/2890): ID 12272 Year 2019

Processing (192/2890): ID 19665 Year 2019

Processing (193/2890): ID 17281 Year 2019

Processing (194/2890): ID 12972 Year 2019

Processing (195/2890): ID 17192 Year 2019

Processing (196/2890): ID 16350 Year 2019

Processing (197/2890): ID 11964 Year 2019

Processing (198/2890): ID 13470 Year 2019

Processing (199/2890): ID 11449 Year 2019

Processing (200/2890): ID 16317 Year 2019

--- Checkpoint saved.

Processing (201/2890): ID 14509 Year 2019

Processing (202/2890): ID 2859 Year 2019

Processing (203/2890): ID 13403 Year 2019

Processing (204/2890): ID 17496 Year 2019

Processing (205/2890): ID 19312 Year 2025

Processing (206/2890): ID 16256 Year 2025

Processing (207/2890): ID 27758 Year 2025

Processing (208/2890): ID 15454 Year 2025

Processing (209/2890): ID 22201 Year 2025

Processing (210/2890): ID 15440 Year 2025

--- Checkpoint saved.

Processing (211/2890): ID 27694 Year 2025

Processing (212/2890): ID 31827 Year 2025

Processing (213/2890): ID 19899 Year 2025

Processing (214/2890): ID 27646 Year 2025

Processing (215/2890): ID 27470 Year 2025

Processing (216/2890): ID 30055 Year 2025

Processing (217/2890): ID 22264 Year 2025

Processing (218/2890): ID 31843 Year 2025

Processing (219/2890): ID 16944 Year 2025

Processing (220/2890): ID 27782 Year 2025

--- Checkpoint saved.

Processing (221/2890): ID 27487 Year 2025

Processing (222/2890): ID 20302 Year 2025

Processing (223/2890): ID 11486 Year 2025

Processing (224/2890): ID 18525 Year 2025

Processing (225/2890): ID 27707 Year 2025

Processing (226/2890): ID 30056 Year 2025

Processing (227/2890): ID 29878 Year 2025

Processing (228/2890): ID 20492 Year 2025

Processing (229/2890): ID 13743 Year 2025

Processing (230/2890): ID 27500 Year 2025

--- Checkpoint saved.

Processing (231/2890): ID 30279 Year 2025

Processing (232/2890): ID 13774 Year 2025

Processing (233/2890): ID 26221 Year 2025

Processing (234/2890): ID 30146 Year 2025

Processing (235/2890): ID 12304 Year 2025

Processing (236/2890): ID 19959 Year 2025

Processing (237/2890): ID 26378 Year 2025

Processing (238/2890): ID 13164 Year 2025

Processing (239/2890): ID 13361 Year 2018

Processing (240/2890): ID 18684 Year 2018

--- Checkpoint saved.

Processing (241/2890): ID 15764 Year 2018

Processing (242/2890): ID 1118 Year 2018

Processing (243/2890): ID 10131 Year 2018

Processing (244/2890): ID 11762 Year 2018

Processing (245/2890): ID 1890 Year 2019

Processing (246/2890): ID 13896 Year 2019

Processing (247/2890): ID 4676 Year 2018

Processing (248/2890): ID 10190 Year 2018

Processing (249/2890): ID 13183 Year 2018

Processing (250/2890): ID 4505 Year 2018

--- Checkpoint saved.

Processing (251/2890): ID 4141 Year 2019

Processing (252/2890): ID 4772 Year 2019

Processing (253/2890): ID 13761 Year 2019

Processing (254/2890): ID 10310 Year 2021

Processing (255/2890): ID 11836 Year 2021

Processing (256/2890): ID 6249 Year 2021

Processing (257/2890): ID 17479 Year 2021

Processing (258/2890): ID 13543 Year 2021

Processing (259/2890): ID 13050 Year 2021

Processing (260/2890): ID 2520 Year 2021

--- Checkpoint saved.

Processing (261/2890): ID 18000 Year 2021

Processing (262/2890): ID 4776 Year 2021

Processing (263/2890): ID 3542 Year 2021

Processing (264/2890): ID 19959 Year 2021

Processing (265/2890): ID 11713 Year 2021

Processing (266/2890): ID 19942 Year 2021

Processing (267/2890): ID 19867 Year 2021

Processing (268/2890): ID 20418 Year 2021

Processing (269/2890): ID 18413 Year 2021

Processing (270/2890): ID 18581 Year 2021

--- Checkpoint saved.

Processing (271/2890): ID 4676 Year 2021

Processing (272/2890): ID 11156 Year 2021

Processing (273/2890): ID 14663 Year 2021

Processing (274/2890): ID 16358 Year 2021

Processing (275/2890): ID 16977 Year 2021

Processing (276/2890): ID 13774 Year 2021

Processing (277/2890): ID 20302 Year 2021

Processing (278/2890): ID 19800 Year 2021

Processing (279/2890): ID 11682 Year 2021

Processing (280/2890): ID 12970 Year 2021

--- Checkpoint saved.

Processing (281/2890): ID 14107 Year 2021

Processing (282/2890): ID 3137 Year 2021

Processing (283/2890): ID 22286 Year 2021

Processing (284/2890): ID 15474 Year 2021

Processing (285/2890): ID 19979 Year 2021

Processing (286/2890): ID 14168 Year 2021

Processing (287/2890): ID 15734 Year 2021

Processing (288/2890): ID 16977 Year 2018

Processing (289/2890): ID 11713 Year 2018

Processing (290/2890): ID 7448 Year 2018

--- Checkpoint saved.

Processing (291/2890): ID 13761 Year 2018

Processing (292/2890): ID 2429 Year 2019

Processing (293/2890): ID 17034 Year 2019

Processing (294/2890): ID 11801 Year 2019

Processing (295/2890): ID 6562 Year 2019

Processing (296/2890): ID 6984 Year 2019

Processing (297/2890): ID 4869 Year 2019

Processing (298/2890): ID 6895 Year 2018

Processing (299/2890): ID 4141 Year 2018

Processing (300/2890): ID 6345 Year 2018

--- Checkpoint saved.

Processing (301/2890): ID 9388 Year 2018

Processing (302/2890): ID 15440 Year 2018

Processing (303/2890): ID 12808 Year 2018

Processing (304/2890): ID 13218 Year 2018

Processing (305/2890): ID 13684 Year 2018

Processing (306/2890): ID 5524 Year 2018

Processing (307/2890): ID 6397 Year 2018

Processing (308/2890): ID 4930 Year 2018

Processing (309/2890): ID 16348 Year 2018

Processing (310/2890): ID 3201 Year 2018

--- Checkpoint saved.

Processing (311/2890): ID 11674 Year 2019

Processing (312/2890): ID 16137 Year 2019

Processing (313/2890): ID 18300 Year 2019

Processing (314/2890): ID 11903 Year 2019

Processing (315/2890): ID 17594 Year 2025

Processing (316/2890): ID 17295 Year 2025

Processing (317/2890): ID 10587 Year 2019

Processing (318/2890): ID 6632 Year 2018

Processing (319/2890): ID 14825 Year 2018

Processing (320/2890): ID 15036 Year 2018

--- Checkpoint saved.

Processing (321/2890): ID 15474 Year 2018

Processing (322/2890): ID 10123 Year 2018

Processing (323/2890): ID 16137 Year 2018

Processing (324/2890): ID 15071 Year 2019

Processing (325/2890): ID 3184 Year 2018

Processing (326/2890): ID 11490 Year 2018

Processing (327/2890): ID 16155 Year 2018

Processing (328/2890): ID 15454 Year 2018

Processing (329/2890): ID 11589 Year 2018

Processing (330/2890): ID 4972 Year 2018

--- Checkpoint saved.

Processing (331/2890): ID 11674 Year 2018

Processing (332/2890): ID 4869 Year 2018

Processing (333/2890): ID 13781 Year 2019

Processing (334/2890): ID 22294 Year 2025

Processing (335/2890): ID 21846 Year 2025

Processing (336/2890): ID 13543 Year 2018

Processing (337/2890): ID 12917 Year 2018

Processing (338/2890): ID 15947 Year 2018

Processing (339/2890): ID 3548 Year 2018

Processing (340/2890): ID 4776 Year 2018

--- Checkpoint saved.

Processing (341/2890): ID 8173 Year 2018

Processing (342/2890): ID 13619 Year 2018

Processing (343/2890): ID 2429 Year 2018

Processing (344/2890): ID 12804 Year 2019

Processing (345/2890): ID 13071 Year 2018

Processing (346/2890): ID 15689 Year 2018

Processing (347/2890): ID 16017 Year 2018

Processing (348/2890): ID 10130 Year 2018

Processing (349/2890): ID 10197 Year 2019

Processing (350/2890): ID 13834 Year 2019

--- Checkpoint saved.

Processing (351/2890): ID 9460 Year 2018

Processing (352/2890): ID 8223 Year 2018

Processing (353/2890): ID 12970 Year 2018

Processing (354/2890): ID 15232 Year 2018

Processing (355/2890): ID 11486 Year 2018

Processing (356/2890): ID 18790 Year 2019

Processing (357/2890): ID 17479 Year 2025

Processing (358/2890): ID 25098 Year 2025

Processing (359/2890): ID 21390 Year 2025

Processing (360/2890): ID 25436 Year 2025

--- Checkpoint saved.

Processing (361/2890): ID 19867 Year 2025

Processing (362/2890): ID 31635 Year 2025

Processing (363/2890): ID 23301 Year 2025

Processing (364/2890): ID 26108 Year 2025

Processing (365/2890): ID 33829 Year 2025

Processing (366/2890): ID 30134 Year 2025

Processing (367/2890): ID 14107 Year 2025

Processing (368/2890): ID 24494 Year 2025

Processing (369/2890): ID 12730 Year 2025

Processing (370/2890): ID 23920 Year 2025

--- Checkpoint saved.

Processing (371/2890): ID 14168 Year 2025

Processing (372/2890): ID 12768 Year 2025

Processing (373/2890): ID 30182 Year 2025

Processing (374/2890): ID 9132 Year 2025

Processing (375/2890): ID 22250 Year 2025

Processing (376/2890): ID 29911 Year 2025

Processing (377/2890): ID 24719 Year 2025

Processing (378/2890): ID 20070 Year 2025

Processing (379/2890): ID 14739 Year 2025

Processing (380/2890): ID 15823 Year 2025

--- Checkpoint saved.

Processing (381/2890): ID 12718 Year 2025

Processing (382/2890): ID 9803 Year 2025

Processing (383/2890): ID 21224 Year 2025

Processing (384/2890): ID 23429 Year 2025

Processing (385/2890): ID 21487 Year 2025

Processing (386/2890): ID 24728 Year 2025

Processing (387/2890): ID 14309 Year 2025

Processing (388/2890): ID 19350 Year 2025

Processing (389/2890): ID 22543 Year 2025

Processing (390/2890): ID 27589 Year 2025

--- Checkpoint saved.

Processing (391/2890): ID 22267 Year 2025

Processing (392/2890): ID 20099 Year 2025

Processing (393/2890): ID 11674 Year 2025

Processing (394/2890): ID 13431 Year 2025

Processing (395/2890): ID 15890 Year 2025

Processing (396/2890): ID 15689 Year 2025

Processing (397/2890): ID 26253 Year 2025

Processing (398/2890): ID 17995 Year 2025

Processing (399/2890): ID 10310 Year 2025

Processing (400/2890): ID 25550 Year 2025

--- Checkpoint saved.

Processing (401/2890): ID 15423 Year 2025

Processing (402/2890): ID 17425 Year 2025

Processing (403/2890): ID 14078 Year 2025

Processing (404/2890): ID 25385 Year 2025

Processing (405/2890): ID 9323 Year 2025

Processing (406/2890): ID 22286 Year 2025

Processing (407/2890): ID 3137 Year 2025

Processing (408/2890): ID 16137 Year 2025

Processing (409/2890): ID 19291 Year 2025

Processing (410/2890): ID 12880 Year 2025

--- Checkpoint saved.

Processing (411/2890): ID 30122 Year 2025

Processing (412/2890): ID 21690 Year 2025

Processing (413/2890): ID 33677 Year 2025

Processing (414/2890): ID 8700 Year 2018

Processing (415/2890): ID 8782 Year 2018

Processing (416/2890): ID 13475 Year 2018

Processing (417/2890): ID 13125 Year 2018

Processing (418/2890): ID 14527 Year 2018

Processing (419/2890): ID 6986 Year 2018

Processing (420/2890): ID 11479 Year 2018

--- Checkpoint saved.

Processing (421/2890): ID 9434 Year 2018

Processing (422/2890): ID 3200 Year 2019

Processing (423/2890): ID 17466 Year 2019

Processing (424/2890): ID 14444 Year 2018

Processing (425/2890): ID 12027 Year 2019

Processing (426/2890): ID 9323 Year 2018

Processing (427/2890): ID 14916 Year 2018

Processing (428/2890): ID 2036 Year 2018

Processing (429/2890): ID 14361 Year 2018

Processing (430/2890): ID 11682 Year 2018

--- Checkpoint saved.

Processing (431/2890): ID 3551 Year 2018

Processing (432/2890): ID 3542 Year 2018

Processing (433/2890): ID 7059 Year 2018

Processing (434/2890): ID 12880 Year 2018

Processing (435/2890): ID 8362 Year 2018

Processing (436/2890): ID 3137 Year 2018

Processing (437/2890): ID 13781 Year 2018

Processing (438/2890): ID 6893 Year 2018

Processing (439/2890): ID 14875 Year 2018

Processing (440/2890): ID 12049 Year 2018

--- Checkpoint saved.

Processing (441/2890): ID 9425 Year 2018

Processing (442/2890): ID 1943 Year 2018

Processing (443/2890): ID 15038 Year 2018

Processing (444/2890): ID 18498 Year 2018

Processing (445/2890): ID 13074 Year 2018

Processing (446/2890): ID 10954 Year 2018


In [153]:
write_csv(master_pitcher_logs, "SPGameLogFact.csv")

## 2026 Pitcher Run. Same logic as before, but for 2026 data.

In [19]:
# 1. SETUP & RESUME LOGIC
# Updated file name to avoid overwriting your previous master logs
checkpoint_2026 <- "pitcher_logs_2026_checkpoint.rds"

if (file.exists(checkpoint_2026)) {
  logs_list_2026 <- readRDS(checkpoint_2026)
  
  # Identify already processed combos
  completed_2026 <- bind_rows(logs_list_2026) %>%
    distinct(PitcherID, Year) %>%
    mutate(PitcherID = as.character(PitcherID)) # Safety check for type matching
  
  # Filter the 2026 queue (anti_join removes what we already have)
  queue_2026 <- unique_pitcher_seasons_2026 %>%
    mutate(PitcherID = as.character(PitcherID)) %>%
    anti_join(completed_2026, by = c("PitcherID", "Year"))
  
  message(paste("Resuming 2026 pull... skipping", nrow(completed_2026), "completed combos."))
} else {
  logs_list_2026 <- list()
  queue_2026 <- unique_pitcher_seasons_2026
}

# 2. THE LOOP
if(nrow(queue_2026) > 0) {
  for(i in 1:nrow(queue_2026)) {
    curr_id <- queue_2026$PitcherID[i]
    curr_year <- queue_2026$Year[i]
    
    message(paste0("2026 Task (", i, "/", nrow(queue_2026), "): ID ", curr_id, " Year ", curr_year))
    
    # Try to fetch logs from FanGraphs
    # Note: For the 40 newly added fg_ids with no retro_id, 
    # we are still using their fg_id as the playerid.
    log_data <- tryCatch({
      fg_pitcher_game_logs(playerid = curr_id, year = curr_year)
    }, error = function(e) {
      if (grepl("403", e$message) || grepl("payload", e$message)) {
        message("!!! API Limit Hit. Cooling down for 120 seconds...")
        Sys.sleep(120) 
        return(NULL)
      }
      return(NULL)
    })
    
    # 3. VALIDATION & STORAGE
    if(!is.null(log_data) && nrow(log_data) > 0) {
      log_data$PitcherID <- curr_id
      log_data$Year <- curr_year
      logs_list_2026[[length(logs_list_2026) + 1]] <- log_data
    }
    
    # Checkpoint every 10 pitchers
    if (i %% 10 == 0) {
      saveRDS(logs_list_2026, checkpoint_2026)
      message("--- 2026 Checkpoint saved.")
    }
    
    # Variable sleep to mimic human browsing and avoid IP bans
    Sys.sleep(runif(1, 1.8, 3.8))
  }
}

# 4. FINAL ASSEMBLY
pitcher_logs_2026_final <- bind_rows(logs_list_2026)
saveRDS(pitcher_logs_2026_final, "pitcher_logs_2026_final.rds")
message("2026 Process Complete! File saved as pitcher_logs_2026_final.rds")

2026 Task (1/671): ID 19312 Year 2026

2026 Task (2/671): ID 16256 Year 2026

2026 Task (3/671): ID 27758 Year 2026

2026 Task (4/671): ID 15454 Year 2026

2026 Task (5/671): ID 22201 Year 2026

2026 Task (6/671): ID 15440 Year 2026

2026 Task (7/671): ID 27694 Year 2026

2026 Task (8/671): ID 31827 Year 2026

2026-04-24 02:04:34.27841: Invalid arguments or no pitcher game log data available!

2026 Task (9/671): ID 19899 Year 2026

2026-04-24 02:04:36.647829: Invalid arguments or no pitcher game log data available!

2026 Task (10/671): ID 27646 Year 2026

2026-04-24 02:04:39.046225: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (11/671): ID 27470 Year 2026

2026 Task (12/671): ID 30055 Year 2026

2026 Task (13/671): ID 22264 Year 2026

2026 Task (14/671): ID 31843 Year 2026

2026 Task (15/671): ID 16944 Year 2026

2026 Task (16/671): ID 27782 Year 2026

2026 Task (17/671): ID 27487 Year 2026

2026-04-24 02:05:00.490103: Invalid arguments or no pitcher game log data available!

2026 Task (18/671): ID 20302 Year 2026

2026 Task (19/671): ID 11486 Year 2026

2026 Task (20/671): ID 18525 Year 2026

--- 2026 Checkpoint saved.

2026 Task (21/671): ID 27707 Year 2026

2026 Task (22/671): ID 30056 Year 2026

2026-04-24 02:05:15.833642: Invalid arguments or no pitcher game log data available!

2026 Task (23/671): ID 29878 Year 2026

2026 Task (24/671): ID 20492 Year 2026

2026 Task (25/671): ID 13743 Year 2026

2026 Task (26/671): ID 27500 Year 2026

2026 Task (27/671): ID 30279 Year 2026

2026 Task (28/671): ID 13774 Year 2026

2026 Task (29/671): ID 26221 Year 2026

2026-04-24 02:05:35.7242: Invalid arguments or no pitcher game log data available!

2026 Task (30/671): ID 30146 Year 2026

--- 2026 Checkpoint saved.

2026 Task (31/671): ID 12304 Year 2026

2026 Task (32/671): ID 19959 Year 2026

2026 Task (33/671): ID 26378 Year 2026

2026-04-24 02:05:48.712592: Invalid arguments or no pitcher game log data available!

2026 Task (34/671): ID 13164 Year 2026

2026 Task (35/671): ID 17594 Year 2026

2026 Task (36/671): ID 17295 Year 2026

2026 Task (37/671): ID 22294 Year 2026

2026 Task (38/671): ID 21846 Year 2026

2026 Task (39/671): ID 17479 Year 2026

2026 Task (40/671): ID 25098 Year 2026

--- 2026 Checkpoint saved.

2026 Task (41/671): ID 21390 Year 2026

2026 Task (42/671): ID 25436 Year 2026

2026 Task (43/671): ID 19867 Year 2026

2026-04-24 02:06:18.778657: Invalid arguments or no pitcher game log data available!

2026 Task (44/671): ID 31635 Year 2026

2026-04-24 02:06:21.265349: Invalid arguments or no pitcher game log data available!

2026 Task (45/671): ID 23301 Year 2026

2026 Task (46/671): ID 26108 Year 2026

2026 Task (47/671): ID 33829 Year 2026

2026 Task (48/671): ID 30134 Year 2026

2026 Task (49/671): ID 14107 Year 2026

2026 Task (50/671): ID 24494 Year 2026

--- 2026 Checkpoint saved.

2026 Task (51/671): ID 12730 Year 2026

2026 Task (52/671): ID 23920 Year 2026

2026 Task (53/671): ID 14168 Year 2026

2026-04-24 02:06:48.401647: Invalid arguments or no pitcher game log data available!

2026 Task (54/671): ID 12768 Year 2026

2026 Task (55/671): ID 30182 Year 2026

2026 Task (56/671): ID 9132 Year 2026

2026 Task (57/671): ID 22250 Year 2026

2026 Task (58/671): ID 29911 Year 2026

2026 Task (59/671): ID 24719 Year 2026

2026 Task (60/671): ID 20070 Year 2026

--- 2026 Checkpoint saved.

2026 Task (61/671): ID 14739 Year 2026

2026 Task (62/671): ID 15823 Year 2026

2026 Task (63/671): ID 12718 Year 2026

2026 Task (64/671): ID 9803 Year 2026

2026 Task (65/671): ID 21224 Year 2026

2026 Task (66/671): ID 23429 Year 2026

2026-04-24 02:07:26.925902: Invalid arguments or no pitcher game log data available!

2026 Task (67/671): ID 21487 Year 2026

2026-04-24 02:07:29.847636: Invalid arguments or no pitcher game log data available!

2026 Task (68/671): ID 24728 Year 2026

2026 Task (69/671): ID 14309 Year 2026

2026-04-24 02:07:36.661113: Invalid arguments or no pitcher game log data available!

2026 Task (70/671): ID 19350 Year 2026

--- 2026 Checkpoint saved.

2026 Task (71/671): ID 22543 Year 2026

2026 Task (72/671): ID 27589 Year 2026

2026-04-24 02:07:45.499789: Invalid arguments or no pitcher game log data available!

2026 Task (73/671): ID 22267 Year 2026

2026 Task (74/671): ID 20099 Year 2026

2026 Task (75/671): ID 11674 Year 2026

2026 Task (76/671): ID 13431 Year 2026

2026-04-24 02:07:57.845875: Invalid arguments or no pitcher game log data available!

2026 Task (77/671): ID 15890 Year 2026

2026 Task (78/671): ID 15689 Year 2026

2026 Task (79/671): ID 26253 Year 2026

2026 Task (80/671): ID 17995 Year 2026

--- 2026 Checkpoint saved.

2026 Task (81/671): ID 10310 Year 2026

2026-04-24 02:08:12.923507: Invalid arguments or no pitcher game log data available!

2026 Task (82/671): ID 25550 Year 2026

2026 Task (83/671): ID 15423 Year 2026

2026-04-24 02:08:17.564821: Invalid arguments or no pitcher game log data available!

2026 Task (84/671): ID 17425 Year 2026

2026 Task (85/671): ID 14078 Year 2026

2026 Task (86/671): ID 25385 Year 2026

2026 Task (87/671): ID 9323 Year 2026

2026 Task (88/671): ID 22286 Year 2026

2026 Task (89/671): ID 3137 Year 2026

2026 Task (90/671): ID 16137 Year 2026

2026-04-24 02:08:40.586578: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (91/671): ID 19291 Year 2026

2026 Task (92/671): ID 12880 Year 2026

2026-04-24 02:08:47.356063: Invalid arguments or no pitcher game log data available!

2026 Task (93/671): ID 30122 Year 2026

2026 Task (94/671): ID 21690 Year 2026

2026 Task (95/671): ID 33677 Year 2026

2026 Task (96/671): ID 27472 Year 2026

2026 Task (97/671): ID 26048 Year 2026

2026-04-24 02:09:01.378802: Invalid arguments or no pitcher game log data available!

2026 Task (98/671): ID 27756 Year 2026

2026 Task (99/671): ID 21504 Year 2026

2026 Task (100/671): ID 11426 Year 2026

--- 2026 Checkpoint saved.

2026 Task (101/671): ID 26440 Year 2026

2026 Task (102/671): ID 30184 Year 2026

2026 Task (103/671): ID 11156 Year 2026

2026 Task (104/671): ID 27768 Year 2026

2026 Task (105/671): ID 18684 Year 2026

2026 Task (106/671): ID 27463 Year 2026

2026 Task (107/671): ID 35333 Year 2026

2026 Task (108/671): ID 33825 Year 2026

2026 Task (109/671): ID 31687 Year 2026

2026 Task (110/671): ID 19388 Year 2026

2026-04-24 02:09:39.461643: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (111/671): ID 15474 Year 2026

2026-04-24 02:09:42.809958: Invalid arguments or no pitcher game log data available!

2026 Task (112/671): ID 22100 Year 2026

2026 Task (113/671): ID 13932 Year 2026

2026 Task (114/671): ID 17677 Year 2026

2026 Task (115/671): ID 35321 Year 2026

2026 Task (116/671): ID 14120 Year 2026

2026 Task (117/671): ID 12317 Year 2026

2026 Task (118/671): ID 30113 Year 2026

2026 Task (119/671): ID 15038 Year 2026

2026 Task (120/671): ID 27552 Year 2026

--- 2026 Checkpoint saved.

2026 Task (121/671): ID 6893 Year 2026

2026-04-24 02:10:11.367409: Invalid arguments or no pitcher game log data available!

2026 Task (122/671): ID 13896 Year 2026

2026-04-24 02:10:15.084364: Invalid arguments or no pitcher game log data available!

2026 Task (123/671): ID 12049 Year 2026

2026-04-24 02:10:18.056622: Invalid arguments or no pitcher game log data available!

2026 Task (124/671): ID 27483 Year 2026

2026-04-24 02:10:21.647947: Invalid arguments or no pitcher game log data available!

2026 Task (125/671): ID 19755 Year 2026

2026 Task (126/671): ID 20423 Year 2026

2026 Task (127/671): ID 25977 Year 2026

2026-04-24 02:10:32.092237: Invalid arguments or no pitcher game log data available!

2026 Task (128/671): ID 20000 Year 2026

2026 Task (129/671): ID 17874 Year 2026

2026-04-24 02:10:36.954292: Invalid arguments or no pitcher game log data available!

2026 Task (130/671): ID 19427 Year 2026

2026-04-24 02:10:40.493793: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (131/671): ID 17149 Year 2026

2026-04-24 02:10:44.136849: Invalid arguments or no pitcher game log data available!

2026 Task (132/671): ID 20191 Year 2026

2026 Task (133/671): ID 27468 Year 2026

2026 Task (134/671): ID 13125 Year 2026

2026-04-24 02:10:52.233549: Invalid arguments or no pitcher game log data available!

2026 Task (135/671): ID 6902 Year 2026

2026 Task (136/671): ID 26285 Year 2026

2026-04-24 02:10:57.7984: Invalid arguments or no pitcher game log data available!

2026 Task (137/671): ID 6562 Year 2026

2026-04-24 02:11:00.7038: Invalid arguments or no pitcher game log data available!

2026 Task (138/671): ID 12777 Year 2026

2026-04-24 02:11:03.904003: Invalid arguments or no pitcher game log data available!

2026 Task (139/671): ID 13050 Year 2026

2026-04-24 02:11:06.540555: Invalid arguments or no pitcher game log data available!

2026 Task (140/671): ID 19695 Year 2026

--- 2026 Checkpoint saved.

2026 Task (141/671): ID 22182 Year 2026

2026-04-24 02:11:12.523351: Invalid arguments or no pitcher game log data available!

2026 Task (142/671): ID 11760 Year 2026

2026-04-24 02:11:15.451846: Invalid arguments or no pitcher game log data available!

2026 Task (143/671): ID 20633 Year 2026

2026 Task (144/671): ID 19866 Year 2026

2026-04-24 02:11:22.173957: Invalid arguments or no pitcher game log data available!

2026 Task (145/671): ID 19407 Year 2026

2026-04-24 02:11:25.586764: Invalid arguments or no pitcher game log data available!

2026 Task (146/671): ID 16918 Year 2026

2026 Task (147/671): ID 18679 Year 2026

2026 Task (148/671): ID 13781 Year 2026

2026-04-24 02:11:33.900302: Invalid arguments or no pitcher game log data available!

2026 Task (149/671): ID 19361 Year 2026

2026-04-24 02:11:36.495129: Invalid arguments or no pitcher game log data available!

2026 Task (150/671): ID 13543 Year 2026

2026-04-24 02:11:40.007425: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (151/671): ID 23150 Year 2026

2026 Task (152/671): ID 27451 Year 2026

2026-04-24 02:11:46.434917: Invalid arguments or no pitcher game log data available!

2026 Task (153/671): ID 8700 Year 2026

2026 Task (154/671): ID 23899 Year 2026

2026 Task (155/671): ID 27889 Year 2026

2026 Task (156/671): ID 27688 Year 2026

2026 Task (157/671): ID 27474 Year 2026

2026 Task (158/671): ID 25880 Year 2026

2026 Task (159/671): ID 18674 Year 2026

2026 Task (160/671): ID 16977 Year 2026

2026-04-24 02:12:12.400031: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (161/671): ID 18383 Year 2026

2026 Task (162/671): ID 19479 Year 2026

2026 Task (163/671): ID 30076 Year 2026

2026 Task (164/671): ID 31730 Year 2026

2026 Task (165/671): ID 14374 Year 2026

2026 Task (166/671): ID 21741 Year 2026

2026 Task (167/671): ID 24763 Year 2026

2026 Task (168/671): ID 25377 Year 2026

2026 Task (169/671): ID 2036 Year 2026

2026-04-24 02:12:39.771012: Invalid arguments or no pitcher game log data available!

2026 Task (170/671): ID 23590 Year 2026

--- 2026 Checkpoint saved.

2026 Task (171/671): ID 21455 Year 2026

2026 Task (172/671): ID 17277 Year 2026

2026 Task (173/671): ID 17312 Year 2026

2026-04-24 02:12:52.621129: Invalid arguments or no pitcher game log data available!

2026 Task (174/671): ID 19911 Year 2026

2026 Task (175/671): ID 19447 Year 2026

2026-04-24 02:12:58.437424: Invalid arguments or no pitcher game log data available!

2026 Task (176/671): ID 12447 Year 2026

2026 Task (177/671): ID 22487 Year 2026

2026 Task (178/671): ID 19853 Year 2026

2026 Task (179/671): ID 8779 Year 2026

2026-04-24 02:13:10.573501: Invalid arguments or no pitcher game log data available!

2026 Task (180/671): ID 17085 Year 2026

2026-04-24 02:13:14.300645: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (181/671): ID 19244 Year 2026

2026-04-24 02:13:16.570591: Invalid arguments or no pitcher game log data available!

2026 Task (182/671): ID 25386 Year 2026

2026-04-24 02:13:19.105451: Invalid arguments or no pitcher game log data available!

2026 Task (183/671): ID 6895 Year 2026

2026-04-24 02:13:21.606477: Invalid arguments or no pitcher game log data available!

2026 Task (184/671): ID 25463 Year 2026

2026 Task (185/671): ID 12808 Year 2026

2026-04-24 02:13:28.962588: Invalid arguments or no pitcher game log data available!

2026 Task (186/671): ID 25777 Year 2026

2026-04-24 02:13:30.97418: Invalid arguments or no pitcher game log data available!

2026 Task (187/671): ID 14932 Year 2026

2026-04-24 02:13:34.202877: Invalid arguments or no pitcher game log data available!

2026 Task (188/671): ID 7593 Year 2026

2026-04-24 02:13:37.13634: Invalid arguments or no pitcher game log data available!

2026 Task (189/671): ID 19784 Year 2026

2026-04-24 02:13:40.392091: Invalid arguments or no pitcher game log data available!

2026 Task (190/671): ID 2520 Year 2026

2026-04-24 02:13:43.964702: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (191/671): ID 11828 Year 2026

2026-04-24 02:13:46.691694: Invalid arguments or no pitcher game log data available!

2026 Task (192/671): ID 31508 Year 2026

2026-04-24 02:13:49.436305: Invalid arguments or no pitcher game log data available!

2026 Task (193/671): ID 19716 Year 2026

2026 Task (194/671): ID 27863 Year 2026

2026-04-24 02:13:55.094881: Invalid arguments or no pitcher game log data available!

2026 Task (195/671): ID 16511 Year 2026

2026-04-24 02:13:58.389359: Invalid arguments or no pitcher game log data available!

2026 Task (196/671): ID 21537 Year 2026

2026 Task (197/671): ID 35456 Year 2026

2026-04-24 02:14:05.044556: Invalid arguments or no pitcher game log data available!

2026 Task (198/671): ID 18498 Year 2026

2026-04-24 02:14:08.337115: Invalid arguments or no pitcher game log data available!

2026 Task (199/671): ID 6797 Year 2026

2026-04-24 02:14:11.644396: Invalid arguments or no pitcher game log data available!

2026 Task (200/671): ID 10591 Year 2026

2026-04-24 02:14:15.048868: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (201/671): ID 22191 Year 2026

2026 Task (202/671): ID 33699 Year 2026

2026-04-24 02:14:20.166136: Invalid arguments or no pitcher game log data available!

2026 Task (203/671): ID 27636 Year 2026

2026 Task (204/671): ID 29914 Year 2026

2026 Task (205/671): ID 19222 Year 2026

2026 Task (206/671): ID 16561 Year 2026

2026-04-24 02:14:33.456421: Invalid arguments or no pitcher game log data available!

2026 Task (207/671): ID 21267 Year 2026

2026 Task (208/671): ID 21318 Year 2026

2026-04-24 02:14:38.018391: Invalid arguments or no pitcher game log data available!

2026 Task (209/671): ID 24968 Year 2026

2026-04-24 02:14:41.71649: Invalid arguments or no pitcher game log data available!

2026 Task (210/671): ID 10123 Year 2026

2026-04-24 02:14:43.848413: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (211/671): ID 14843 Year 2026

2026 Task (212/671): ID 20548 Year 2026

2026-04-24 02:14:48.813352: Invalid arguments or no pitcher game log data available!

2026 Task (213/671): ID 29960 Year 2026

2026-04-24 02:14:52.096747: Invalid arguments or no pitcher game log data available!

2026 Task (214/671): ID 27572 Year 2026

2026 Task (215/671): ID 10603 Year 2026

2026 Task (216/671): ID 11589 Year 2026

2026-04-24 02:14:59.691759: Invalid arguments or no pitcher game log data available!

2026 Task (217/671): ID 31838 Year 2026

2026 Task (218/671): ID 19879 Year 2026

2026-04-24 02:15:05.699371: Invalid arguments or no pitcher game log data available!

2026 Task (219/671): ID 16358 Year 2026

2026 Task (220/671): ID 4676 Year 2026

2026-04-24 02:15:11.821854: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (221/671): ID 20778 Year 2026

2026 Task (222/671): ID 31846 Year 2026

2026-04-24 02:15:20.232002: Invalid arguments or no pitcher game log data available!

2026 Task (223/671): ID 27669 Year 2026

2026 Task (224/671): ID 22630 Year 2026

2026 Task (225/671): ID 21448 Year 2026

2026 Task (226/671): ID 15488 Year 2026

2026 Task (227/671): ID 13649 Year 2026

2026 Task (228/671): ID 27779 Year 2026

2026 Task (229/671): ID 19990 Year 2026

2026-04-24 02:15:40.624692: Invalid arguments or no pitcher game log data available!

2026 Task (230/671): ID 16149 Year 2026

--- 2026 Checkpoint saved.

2026 Task (231/671): ID 19618 Year 2026

2026 Task (232/671): ID 11423 Year 2026

2026 Task (233/671): ID 26419 Year 2026

2026-04-24 02:15:52.816751: Invalid arguments or no pitcher game log data available!

2026 Task (234/671): ID 15734 Year 2026

2026 Task (235/671): ID 10954 Year 2026

2026 Task (236/671): ID 29837 Year 2026

2026-04-24 02:16:02.271301: Invalid arguments or no pitcher game log data available!

2026 Task (237/671): ID 30203 Year 2026

2026-04-24 02:16:05.378046: Invalid arguments or no pitcher game log data available!

2026 Task (238/671): ID 26231 Year 2026

2026 Task (239/671): ID 23796 Year 2026

2026 Task (240/671): ID 29866 Year 2026

2026-04-24 02:16:15.649605: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (241/671): ID 13942 Year 2026

2026 Task (242/671): ID 15094 Year 2026

2026-04-24 02:16:20.84707: Invalid arguments or no pitcher game log data available!

2026 Task (243/671): ID 20045 Year 2026

2026-04-24 02:16:23.474142: Invalid arguments or no pitcher game log data available!

2026 Task (244/671): ID 27498 Year 2026

2026-04-24 02:16:25.445517: Invalid arguments or no pitcher game log data available!

2026 Task (245/671): ID 19374 Year 2026

2026 Task (246/671): ID 30133 Year 2026

2026 Task (247/671): ID 22253 Year 2026

2026-04-24 02:16:33.750429: Invalid arguments or no pitcher game log data available!

2026 Task (248/671): ID 18694 Year 2026

2026 Task (249/671): ID 11836 Year 2026

2026 Task (250/671): ID 22207 Year 2026

--- 2026 Checkpoint saved.

2026 Task (251/671): ID 16502 Year 2026

2026 Task (252/671): ID 30160 Year 2026

2026-04-24 02:16:46.649641: Invalid arguments or no pitcher game log data available!

2026 Task (253/671): ID 30002 Year 2026

2026-04-24 02:16:50.078351: Invalid arguments or no pitcher game log data available!

2026 Task (254/671): ID 6632 Year 2026

2026-04-24 02:16:52.200807: Invalid arguments or no pitcher game log data available!

2026 Task (255/671): ID 20132 Year 2026

2026-04-24 02:16:55.287469: Invalid arguments or no pitcher game log data available!

2026 Task (256/671): ID 16400 Year 2026

2026 Task (257/671): ID 6107 Year 2026

2026 Task (258/671): ID 18311 Year 2026

2026-04-24 02:17:04.332325: Invalid arguments or no pitcher game log data available!

2026 Task (259/671): ID 27668 Year 2026

2026 Task (260/671): ID 14916 Year 2026

2026-04-24 02:17:11.714537: Invalid arguments or no pitcher game log data available!

--- 2026 Checkpoint saved.

2026 Task (261/671): ID 20531 Year 2026

2026-04-24 02:17:14.482198: Invalid arguments or no pitcher game log data available!

2026 Task (262/671): ID 16835 Year 2026

2026 Task (263/671): ID 16943 Year 2026

2026 Task (264/671): ID 21446 Year 2026

2026 Task (265/671): ID 15145 Year 2026

2026 Task (266/671): ID 19874 Year 2026

2026-04-24 02:17:30.001004: Invalid arguments or no pitcher game log data available!

2026 Task (267/671): ID 21584 Year 2026

2026-04-24 02:17:33.776438: Invalid arguments or no pitcher game log data available!

2026 Task (268/671): ID 26058 Year 2026

2026-04-24 02:17:37.079791: Invalid arguments or no pitcher game log data available!

2026 Task (269/671): ID 27597 Year 2026

2026-04-24 02:17:39.399387: Invalid arguments or no pitcher game log data available!


In [21]:
write_csv(pitcher_logs_2026_final, "StartingPGameLogFact2026.csv")

In [4]:
# Compile a tibble of unique combinations of batter IDs and year for game log data gathering.

unique_hitter_seasons <- GBSHitting %>%
  select(Year, HomeBatter1IDFG, HomeBatter2IDFG, HomeBatter3IDFG, HomeBatter4IDFG, HomeBatter5IDFG, HomeBatter6IDFG, HomeBatter7IDFG, HomeBatter8IDFG, HomeBatter9IDFG,
   AwayBatter1IDFG, AwayBatter2IDFG, AwayBatter3IDFG, AwayBatter4IDFG, AwayBatter5IDFG, AwayBatter6IDFG, AwayBatter7IDFG, AwayBatter8IDFG, AwayBatter9IDFG) %>%
  pivot_longer(
    cols = c(HomeBatter1IDFG, HomeBatter2IDFG, HomeBatter3IDFG, HomeBatter4IDFG, HomeBatter5IDFG, HomeBatter6IDFG, HomeBatter7IDFG, HomeBatter8IDFG, HomeBatter9IDFG,
   AwayBatter1IDFG, AwayBatter2IDFG, AwayBatter3IDFG, AwayBatter4IDFG, AwayBatter5IDFG, AwayBatter6IDFG, AwayBatter7IDFG, AwayBatter8IDFG, AwayBatter9IDFG), 
    names_to = "Side", 
    values_to = "BatterID"
  ) %>%
  # Keep only one row per Pitcher/Season
  distinct(BatterID, Year)

# View the result
print(unique_hitter_seasons)

# A tibble: 5,866 × 2
   BatterID  Year
      <dbl> <dbl>
 1    22266  2024
 2    22275  2024
 3    19913  2024
 4    24703  2024
 5    26151  2024
 6    19608  2024
 7    20536  2024
 8    16947  2024
 9    18551  2024
10    18568  2024
# ℹ 5,856 more rows

In [7]:
write_csv(unique_hitter_seasons, "uhs.csv")

In [20]:
unique_hitter_seasons_temp <- read_csv('/Users/owendrummond/Documents/python_projects/Capstone/uhs.csv')

Rows: 5866 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
dbl (2): BatterID, Year

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [22]:
unique_hitter_seasons_2026 <- unique_hitter_seasons_temp %>%
  filter(Year >= 2023) %>%
  select(BatterID) %>%
  distinct() %>%
  mutate(
    BatterID = as.character(BatterID),
    Year = 2026
  )

# 2. Get fg_id, ensure it is character, and rename
new_batter_ids <- player_dim %>%
  filter(is.na(retro_id) | retro_id == "") %>%
  select(BatterID = fg_id) %>%
  mutate(
    BatterID = as.character(BatterID),
    Year = 2026
  )

In [23]:
unique_hitter_seasons_2026 <- bind_rows(unique_hitter_seasons_2026, new_batter_ids)

In [25]:
fg_batter_game_logs(playerid = unique_hitter_seasons_2026$BatterID[1],year = unique_hitter_seasons_2026$Year[1])

   PlayerName     playerid Date       Team Opp  season Age BatOrder Pos G ⋯
1  Xavier Edwards 22266    2026-04-22 MIA  STL  2026   26  2        DH  1 ⋯
2  Xavier Edwards 22266    2026-04-21 MIA  STL  2026   26  4        2B  1 ⋯
3  Xavier Edwards 22266    2026-04-20 MIA  STL  2026   26  4        2B  1 ⋯
4  Xavier Edwards 22266    2026-04-19 MIA  MIL  2026   26  2        2B  1 ⋯
5  Xavier Edwards 22266    2026-04-18 MIA  MIL  2026   26  2        2B  1 ⋯
6  Xavier Edwards 22266    2026-04-17 MIA  MIL  2026   26  2        2B  1 ⋯
7  Xavier Edwards 22266    2026-04-15 MIA  @ATL 2026   26  2        2B  1 ⋯
8  Xavier Edwards 22266    2026-04-14 MIA  @ATL 2026   26  2        2B  1 ⋯
9  Xavier Edwards 22266    2026-04-13 MIA  @ATL 2026   26  2        2B  1 ⋯
10 Xavier Edwards 22266    2026-04-12 MIA  @DET 2026   26  7        2B  1 ⋯
11 Xavier Edwards 22266    2026-04-11 MIA  @DET 2026   26  2        2B  1 ⋯
12 Xavier Edwards 22266    2026-04-10 MIA  @DET 2026   26  2        2B  1 ⋯
13 Xavier Edwards 22266    2026-04-09 MIA  CIN  2026   26  2        2B  1 ⋯
14 Xavier Edwards 22266    2026-04-08 MIA  CIN  2026   26  2        2B  1 ⋯
15 Xavier Edwards 22266    2026-04-07 MIA  CIN  2026   26  7        2B  1 ⋯
16 Xavier Edwards 22266    2026-04-06 MIA  CIN  2026   26  7        DH  1 ⋯
17 Xavier Edwards 22266    2026-04-05 MIA  @NYY 2026   26  7        2B  1 ⋯
18 Xavier Edwards 22266    2026-04-04 MIA  @NYY 2026   26  7        2B  1 ⋯
19 Xavier Edwards 22266    2026-04-03 MIA  @NYY 2026   26  2        2B  1 ⋯
20 Xavier Edwards 22266    2026-04-01 MIA  CHW  2026   26  2        2B  1 ⋯
21 Xavier Edwards 22266    2026-03-31 MIA  CHW  2026   26  2        2B  1 ⋯
22 Xavier Edwards 22266    2026-03-30 MIA  CHW  2026   26  2        2B  1 ⋯
23 Xavier Edwards 22266    2026-03-29 MIA  COL  2026   26  7        2B  1 ⋯
24 Xavier Edwards 22266    2026-03-28 MIA  COL  2026   26  2        2B  1 ⋯
25 Xavier Edwards 22266    2026-03-27 MIA  COL  2026   26  7        2B  1 ⋯
   Events EV       LA          Barrels Barrel%   maxEV HardHit HardHit%
1  4      94.02500  -4.0000000 0       0.0000000  98.4 3       0.7500000
2  4      92.65000  27.7500000 0       0.0000000  99.2 2       0.5000000
3  2      79.75000 -12.0000000 1       0.5000000  99.2 1       0.5000000
4  2      89.95000  -6.0000000 0       0.0000000  91.8 0       0.0000000
5  3      91.43333  22.6666667 0       0.0000000  94.5 0       0.0000000
6  4      97.15000  32.0000000 2       0.5000000 103.7 3       0.7500000
7  4      88.40000  -9.2500000 0       0.0000000 101.7 2       0.5000000
8  3      79.56667  -5.6666667 0       0.0000000  95.7 1       0.3333333
9  3      95.10000  13.0000000 1       0.3333333  98.2 2       0.6666667
10 4      90.30000  17.5000000 0       0.0000000  98.5 2       0.5000000
11 4      84.35000  14.0000000 0       0.0000000  91.6 0       0.0000000
12 2      93.45000   9.5000000 0       0.0000000  94.5 0       0.0000000
13 2      96.45000  10.5000000 0       0.0000000  96.8 2       1.0000000
14 3      87.66667   0.3333333 0       0.0000000  99.0 1       0.3333333
15 4      86.37500   1.7500000 0       0.0000000  93.1 0       0.0000000
16 2      91.50000   5.0000000 0       0.0000000  98.9 1       0.5000000
17 4      93.92500  -8.0000000 0       0.0000000 100.6 2       0.5000000
18 4      89.37500  14.5000000 0       0.0000000  97.7 3       0.7500000
19 4      95.55000  24.7500000 1       0.2500000 103.9 3       0.7500000
20 2      92.40000  37.0000000 0       0.0000000  97.0 1       0.5000000
21 4      88.97500  -0.7500000 0       0.0000000  99.6 1       0.2500000
22 3      92.70000   4.6666667 0       0.0000000 100.6 2       0.6666667
23 3      82.15000 -22.0000000 0       0.0000000  99.5 1       0.3333333
24 4      91.75000   5.5000000 0       0.0000000 101.0 3       0.7500000
25 4      87.07500  45.2500000 0       0.0000000  94.9 0       0.0000000
   gamedate   dh
1  2026-04-22 0
2  2026-04-21 0
3  2026-04-20 0
4  2026-04-19 0
5  2026-04-18 0
6  2026-04-17 0
7  2026-04-15 0
8  2026-04-14 0
9  2026-04-13 0
10 2026-04-12 0
11 2026-04-11 0
12 2026-04-10 0
13 2026-04-09 0
14 2026-04-08 0
15 2026-04-07 0
16 2026-04-06 0
17 2026-04-05 0
18 2026-04-04 0
19 2026-04-03 0
20 2026-04-01 0
21 2026-03-31 0
22 2026-03-30 0
23 2026-03-29 0
24 2026-03-28 0
25 2026-03-27 0

# OG Hitter Run

In [10]:
# Because this function was taking so long to execute, and because I was continually getting thrown HTTP request blockers, I had some some A.I. enhancements
# to avoid these blockages such as error detection and periodic sleeps. The idea for the function however, was my own.

# SETUP RESUME LOGIC & HITTER-SPECIFIC FILENAMES
checkpoint_file <- "master_hitter_logs_checkpoint.rds"

if (file.exists(checkpoint_file)) {
  all_hitter_logs_list <- readRDS(checkpoint_file)
  # Identify which ID/Year combos we already have
  completed <- bind_rows(all_hitter_logs_list) %>%
    distinct(BatterID, Year)
  
  # Filter our queue to only include those NOT in the completed list
  queue <- unique_hitter_seasons %>%
    anti_join(completed, by = c("BatterID" = "BatterID", "Year" = "Year"))
  
  message(paste("Resuming... skipping", nrow(completed), "already downloaded hitter combos."))
} else {
  all_hitter_logs_list <- list()
  queue <- unique_hitter_seasons
}

# THE LOOP
for(i in 1:nrow(queue)) {
  b_id <- queue$BatterID[i]
  b_year <- queue$Year[i]
  
  message(paste0("Processing Hitter (", i, "/", nrow(queue), "): ID ", b_id, " Year ", b_year))
  
  # Try to get the batter log
  log <- tryCatch({
    # Updated to hitter-specific function
    fg_batter_game_logs(playerid = b_id, year = b_year)
  }, error = function(e) {
    if (grepl("403", e$message) || grepl("payload", e$message)) {
      message("!!! API Blocker/403 detected. Sleeping for 2 minutes to cool down...")
      Sys.sleep(120) 
      return(NULL)
    }
    return(NULL)
  })
  
  # DATA VALIDATION & SAVING
  if(!is.null(log) && nrow(log) > 0) {
    # Ensure columns match join keys
    log$BatterID <- b_id
    log$Year <- b_year
    all_hitter_logs_list[[length(all_hitter_logs_list) + 1]] <- log
  }
  
  # Save a checkpoint every 10 hitters
  if (i %% 10 == 0) {
    saveRDS(all_hitter_logs_list, checkpoint_file)
    message("--- Hitter checkpoint saved.")
  }
  
  # VARIABLE SLEEP
  # Slightly longer random sleep is safer for larger hitter batches
  Sys.sleep(runif(1, 1.8, 4.0))
}

master_hitter_logs <- bind_rows(all_hitter_logs_list)
saveRDS(master_hitter_logs, "master_hitter_logs_final.rds")
message("Process Complete! All hitter logs saved to master_hitter_logs_final.rds")

Resuming... skipping 5370 already downloaded hitter combos.

Processing Hitter (1/496): ID 21622 Year 2025

Processing Hitter (2/496): ID 25805 Year 2025

Processing Hitter (3/496): ID 18821 Year 2025

Processing Hitter (4/496): ID 23968 Year 2025

Processing Hitter (5/496): ID 24770 Year 2025

Processing Hitter (6/496): ID 24782 Year 2025

Processing Hitter (7/496): ID 22165 Year 2024

Processing Hitter (8/496): ID 22566 Year 2025

Processing Hitter (9/496): ID 27784 Year 2024

Processing Hitter (10/496): ID 17452 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (11/496): ID 20538 Year 2025

Processing Hitter (12/496): ID 31793 Year 2025

Processing Hitter (13/496): ID 24605 Year 2024

Processing Hitter (14/496): ID 12147 Year 2025

Processing Hitter (15/496): ID 16686 Year 2024

Processing Hitter (16/496): ID 22274 Year 2025

Processing Hitter (17/496): ID 22707 Year 2025

Processing Hitter (18/496): ID 8610 Year 2019

Processing Hitter (19/496): ID 16291 Year 2019

Processing Hitter (20/496): ID 18679 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (21/496): ID 7555 Year 2019

Processing Hitter (22/496): ID 17948 Year 2019

Processing Hitter (23/496): ID 4403 Year 2019

Processing Hitter (24/496): ID 4881 Year 2019

Processing Hitter (25/496): ID 3708 Year 2019

Processing Hitter (26/496): ID 19677 Year 2019

Processing Hitter (27/496): ID 14111 Year 2019

Processing Hitter (28/496): ID 8782 Year 2019

Processing Hitter (29/496): ID 12699 Year 2019

Processing Hitter (30/496): ID 16207 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (31/496): ID 17490 Year 2019

Processing Hitter (32/496): ID 19546 Year 2019

Processing Hitter (33/496): ID 13475 Year 2019

Processing Hitter (34/496): ID 5358 Year 2019

Processing Hitter (35/496): ID 15440 Year 2019

Processing Hitter (36/496): ID 11490 Year 2019

Processing Hitter (37/496): ID 18067 Year 2019

Processing Hitter (38/496): ID 13360 Year 2019

Processing Hitter (39/496): ID 10547 Year 2019

Processing Hitter (40/496): ID 14825 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (41/496): ID 14962 Year 2019

Processing Hitter (42/496): ID 14682 Year 2019

Processing Hitter (43/496): ID 5448 Year 2019

Processing Hitter (44/496): ID 12174 Year 2019

Processing Hitter (45/496): ID 16943 Year 2019

Processing Hitter (46/496): ID 17030 Year 2019

Processing Hitter (47/496): ID 12918 Year 2019

Processing Hitter (48/496): ID 4505 Year 2019

Processing Hitter (49/496): ID 19867 Year 2019

Processing Hitter (50/496): ID 12800 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (51/496): ID 18403 Year 2019

Processing Hitter (52/496): ID 10190 Year 2019

Processing Hitter (53/496): ID 13276 Year 2019

Processing Hitter (54/496): ID 15958 Year 2022

Processing Hitter (55/496): ID 12147 Year 2022

Processing Hitter (56/496): ID 30162 Year 2024

Processing Hitter (57/496): ID 24782 Year 2024

Processing Hitter (58/496): ID 19384 Year 2024

Processing Hitter (59/496): ID 15937 Year 2024

Processing Hitter (60/496): ID 19151 Year 2023

--- Hitter checkpoint saved.

Processing Hitter (61/496): ID 20626 Year 2023

Processing Hitter (62/496): ID 18395 Year 2023

Processing Hitter (63/496): ID 25643 Year 2023

Processing Hitter (64/496): ID 24485 Year 2023

Processing Hitter (65/496): ID 22045 Year 2024

Processing Hitter (66/496): ID 17232 Year 2024

Processing Hitter (67/496): ID 16357 Year 2024

Processing Hitter (68/496): ID 19859 Year 2024

Processing Hitter (69/496): ID 10155 Year 2024

Processing Hitter (70/496): ID 15504 Year 2024

--- Hitter checkpoint saved.

Processing Hitter (71/496): ID 27962 Year 2024

Processing Hitter (72/496): ID 25967 Year 2024

Processing Hitter (73/496): ID 22505 Year 2023

Processing Hitter (74/496): ID 20463 Year 2023

Processing Hitter (75/496): ID 19964 Year 2023

Processing Hitter (76/496): ID 28163 Year 2023

Processing Hitter (77/496): ID 22165 Year 2025

Processing Hitter (78/496): ID 16357 Year 2025

Processing Hitter (79/496): ID 23378 Year 2025

Processing Hitter (80/496): ID 17992 Year 2024

--- Hitter checkpoint saved.

Processing Hitter (81/496): ID 5297 Year 2024

Processing Hitter (82/496): ID 19983 Year 2024

Processing Hitter (83/496): ID 14950 Year 2023

Processing Hitter (84/496): ID 16680 Year 2023

Processing Hitter (85/496): ID 27769 Year 2023

Processing Hitter (86/496): ID 24597 Year 2023

Processing Hitter (87/496): ID 22261 Year 2024

Processing Hitter (88/496): ID 17326 Year 2024

Processing Hitter (89/496): ID 26420 Year 2024

Processing Hitter (90/496): ID 25448 Year 2024

--- Hitter checkpoint saved.

Processing Hitter (91/496): ID 16451 Year 2025

Processing Hitter (92/496): ID 19384 Year 2025

Processing Hitter (93/496): ID 20002 Year 2025

Processing Hitter (94/496): ID 12394 Year 2022

Processing Hitter (95/496): ID 19710 Year 2022

Processing Hitter (96/496): ID 19151 Year 2022

Processing Hitter (97/496): ID 19938 Year 2022

Processing Hitter (98/496): ID 5667 Year 2022

Processing Hitter (99/496): ID 12399 Year 2022

Processing Hitter (100/496): ID 10655 Year 2022

--- Hitter checkpoint saved.

Processing Hitter (101/496): ID 12434 Year 2022

Processing Hitter (102/496): ID 16357 Year 2022

Processing Hitter (103/496): ID 19877 Year 2025

Processing Hitter (104/496): ID 31505 Year 2025

Processing Hitter (105/496): ID 27504 Year 2025

Processing Hitter (106/496): ID 31991 Year 2025

Processing Hitter (107/496): ID 25688 Year 2025

Processing Hitter (108/496): ID 33390 Year 2025

Processing Hitter (109/496): ID 25690 Year 2025

Processing Hitter (110/496): ID 33252 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (111/496): ID 16291 Year 2018

Processing Hitter (112/496): ID 31357 Year 2025

Processing Hitter (113/496): ID 15676 Year 2024

Processing Hitter (114/496): ID 34979 Year 2025

Processing Hitter (115/496): ID 33280 Year 2025

Processing Hitter (116/496): ID 19960 Year 2025

Processing Hitter (117/496): ID 19562 Year 2025

Processing Hitter (118/496): ID 10441 Year 2025

Processing Hitter (119/496): ID 9893 Year 2018

Processing Hitter (120/496): ID 15291 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (121/496): ID 12950 Year 2018

Processing Hitter (122/496): ID 7410 Year 2018

Processing Hitter (123/496): ID 9284 Year 2018

Processing Hitter (124/496): ID 13269 Year 2018

Processing Hitter (125/496): ID 7158 Year 2018

Processing Hitter (126/496): ID 1873 Year 2018

Processing Hitter (127/496): ID 13218 Year 2018

Processing Hitter (128/496): ID 10067 Year 2018

Processing Hitter (129/496): ID 29614 Year 2025

Processing Hitter (130/496): ID 27501 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (131/496): ID 21558 Year 2025

Processing Hitter (132/496): ID 29554 Year 2025

Processing Hitter (133/496): ID 31396 Year 2025

Processing Hitter (134/496): ID 23789 Year 2025

Processing Hitter (135/496): ID 26536 Year 2025

Processing Hitter (136/496): ID 12859 Year 2025

Processing Hitter (137/496): ID 21535 Year 2025

Processing Hitter (138/496): ID 22505 Year 2025

Processing Hitter (139/496): ID 14196 Year 2018

Processing Hitter (140/496): ID 17292 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (141/496): ID 8709 Year 2018

Processing Hitter (142/496): ID 12890 Year 2018

Processing Hitter (143/496): ID 16403 Year 2018

Processing Hitter (144/496): ID 17775 Year 2018

Processing Hitter (145/496): ID 17838 Year 2018

Processing Hitter (146/496): ID 10021 Year 2018

Processing Hitter (147/496): ID 12926 Year 2019

Processing Hitter (148/496): ID 14556 Year 2019

Processing Hitter (149/496): ID 11894 Year 2019

Processing Hitter (150/496): ID 5631 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (151/496): ID 12225 Year 2019

Processing Hitter (152/496): ID 16587 Year 2019

Processing Hitter (153/496): ID 13324 Year 2018

Processing Hitter (154/496): ID 17738 Year 2018

Processing Hitter (155/496): ID 16572 Year 2019

Processing Hitter (156/496): ID 13228 Year 2019

Processing Hitter (157/496): ID 29630 Year 2025

Processing Hitter (158/496): ID 23782 Year 2025

Processing Hitter (159/496): ID 21746 Year 2025

Processing Hitter (160/496): ID 28816 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (161/496): ID 29524 Year 2025

Processing Hitter (162/496): ID 29478 Year 2025

Processing Hitter (163/496): ID 19958 Year 2025

Processing Hitter (164/496): ID 21735 Year 2025

Processing Hitter (165/496): ID 13472 Year 2022

Processing Hitter (166/496): ID 13473 Year 2018

Processing Hitter (167/496): ID 15674 Year 2018

Processing Hitter (168/496): ID 22093 Year 2022

Processing Hitter (169/496): ID 9174 Year 2018

Processing Hitter (170/496): ID 14682 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (171/496): ID 26244 Year 2025

Processing Hitter (172/496): ID 4949 Year 2025

Processing Hitter (173/496): ID 24273 Year 2025

Processing Hitter (174/496): ID 15104 Year 2018

Processing Hitter (175/496): ID 19477 Year 2021

Processing Hitter (176/496): ID 27690 Year 2025

Processing Hitter (177/496): ID 16429 Year 2019

Processing Hitter (178/496): ID 6677 Year 2019

Processing Hitter (179/496): ID 11674 Year 2019

Processing Hitter (180/496): ID 12160 Year 2023

--- Hitter checkpoint saved.

Processing Hitter (181/496): ID 19181 Year 2023

Processing Hitter (182/496): ID 17932 Year 2023

Processing Hitter (183/496): ID 21270 Year 2023

Processing Hitter (184/496): ID 17837 Year 2024

Processing Hitter (185/496): ID 18289 Year 2024

Processing Hitter (186/496): ID 24451 Year 2024

Processing Hitter (187/496): ID 29766 Year 2025

Processing Hitter (188/496): ID 25621 Year 2025

Processing Hitter (189/496): ID 26149 Year 2025

Processing Hitter (190/496): ID 27462 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (191/496): ID 12180 Year 2025

Processing Hitter (192/496): ID 22232 Year 2025

Processing Hitter (193/496): ID 31354 Year 2025

Processing Hitter (194/496): ID 24759 Year 2025

Processing Hitter (195/496): ID 25971 Year 2025

Processing Hitter (196/496): ID 25999 Year 2025

Processing Hitter (197/496): ID 23818 Year 2025

Processing Hitter (198/496): ID 29788 Year 2025

Processing Hitter (199/496): ID 13355 Year 2025

Processing Hitter (200/496): ID 19314 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (201/496): ID 24622 Year 2025

Processing Hitter (202/496): ID 16398 Year 2025

Processing Hitter (203/496): ID 19824 Year 2025

Processing Hitter (204/496): ID 5273 Year 2025

Processing Hitter (205/496): ID 27735 Year 2025

Processing Hitter (206/496): ID 20311 Year 2025

Processing Hitter (207/496): ID 11611 Year 2018

Processing Hitter (208/496): ID 12005 Year 2018

Processing Hitter (209/496): ID 17128 Year 2018

Processing Hitter (210/496): ID 14412 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (211/496): ID 15947 Year 2019

Processing Hitter (212/496): ID 5124 Year 2019

Processing Hitter (213/496): ID 23790 Year 2025

Processing Hitter (214/496): ID 26148 Year 2025

Processing Hitter (215/496): ID 9362 Year 2018

Processing Hitter (216/496): ID 12037 Year 2018

Processing Hitter (217/496): ID 29949 Year 2025

Processing Hitter (218/496): ID 31665 Year 2025

Processing Hitter (219/496): ID 21587 Year 2025

Processing Hitter (220/496): ID 19877 Year 2023

--- Hitter checkpoint saved.

Processing Hitter (221/496): ID 4869 Year 2019

Processing Hitter (222/496): ID 15156 Year 2019

Processing Hitter (223/496): ID 10655 Year 2020

Processing Hitter (224/496): ID 15447 Year 2020

Processing Hitter (225/496): ID 30063 Year 2025

Processing Hitter (226/496): ID 27931 Year 2025

Processing Hitter (227/496): ID 15654 Year 2020

Processing Hitter (228/496): ID 16623 Year 2020

Processing Hitter (229/496): ID 13132 Year 2020

Processing Hitter (230/496): ID 13768 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (231/496): ID 19314 Year 2019

Processing Hitter (232/496): ID 20633 Year 2019

Processing Hitter (233/496): ID 9787 Year 2019

Processing Hitter (234/496): ID 5517 Year 2018

Processing Hitter (235/496): ID 4972 Year 2018

Processing Hitter (236/496): ID 7608 Year 2018

Processing Hitter (237/496): ID 13152 Year 2018

Processing Hitter (238/496): ID 14477 Year 2018

Processing Hitter (239/496): ID 4249 Year 2018

Processing Hitter (240/496): ID 17719 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (241/496): ID 10354 Year 2018

Processing Hitter (242/496): ID 15488 Year 2018

Processing Hitter (243/496): ID 11615 Year 2018

Processing Hitter (244/496): ID 13684 Year 2018

Processing Hitter (245/496): ID 14120 Year 2018

Processing Hitter (246/496): ID 13546 Year 2018

Processing Hitter (247/496): ID 16561 Year 2018

Processing Hitter (248/496): ID 16115 Year 2018

Processing Hitter (249/496): ID 9434 Year 2018

Processing Hitter (250/496): ID 17018 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (251/496): ID 13743 Year 2018

Processing Hitter (252/496): ID 17877 Year 2018

Processing Hitter (253/496): ID 13594 Year 2018

Processing Hitter (254/496): ID 13649 Year 2018

Processing Hitter (255/496): ID 18345 Year 2018

Processing Hitter (256/496): ID 12808 Year 2018

Processing Hitter (257/496): ID 2717 Year 2018

Processing Hitter (258/496): ID 19427 Year 2018

Processing Hitter (259/496): ID 17277 Year 2018

Processing Hitter (260/496): ID 9253 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (261/496): ID 10314 Year 2018

Processing Hitter (262/496): ID 13834 Year 2018

Processing Hitter (263/496): ID 10732 Year 2018

Processing Hitter (264/496): ID 6902 Year 2018

Processing Hitter (265/496): ID 10130 Year 2018

Processing Hitter (266/496): ID 8173 Year 2018

Processing Hitter (267/496): ID 17496 Year 2018

Processing Hitter (268/496): ID 15608 Year 2018

Processing Hitter (269/496): ID 15232 Year 2018

Processing Hitter (270/496): ID 1118 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (271/496): ID 16622 Year 2018

Processing Hitter (272/496): ID 17034 Year 2018

Processing Hitter (273/496): ID 13602 Year 2018

Processing Hitter (274/496): ID 15885 Year 2018

Processing Hitter (275/496): ID 2802 Year 2018

Processing Hitter (276/496): ID 6562 Year 2018

Processing Hitter (277/496): ID 10322 Year 2018

Processing Hitter (278/496): ID 16130 Year 2018

Processing Hitter (279/496): ID 15103 Year 2018

Processing Hitter (280/496): ID 6893 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (281/496): ID 14130 Year 2018

Processing Hitter (282/496): ID 12594 Year 2018

Processing Hitter (283/496): ID 4772 Year 2018

Processing Hitter (284/496): ID 9953 Year 2018

Processing Hitter (285/496): ID 15440 Year 2018

Processing Hitter (286/496): ID 6986 Year 2018

Processing Hitter (287/496): ID 13267 Year 2018

Processing Hitter (288/496): ID 11902 Year 2018

Processing Hitter (289/496): ID 19262 Year 2018

Processing Hitter (290/496): ID 7739 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (291/496): ID 3395 Year 2018

Processing Hitter (292/496): ID 13006 Year 2018

Processing Hitter (293/496): ID 18356 Year 2018

Processing Hitter (294/496): ID 13403 Year 2018

Processing Hitter (295/496): ID 16017 Year 2018

Processing Hitter (296/496): ID 11467 Year 2018

Processing Hitter (297/496): ID 14329 Year 2018

Processing Hitter (298/496): ID 14548 Year 2018

Processing Hitter (299/496): ID 13284 Year 2018

Processing Hitter (300/496): ID 16929 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (301/496): ID 17313 Year 2018

Processing Hitter (302/496): ID 12797 Year 2018

Processing Hitter (303/496): ID 15124 Year 2018

Processing Hitter (304/496): ID 11385 Year 2018

Processing Hitter (305/496): ID 15982 Year 2018

Processing Hitter (306/496): ID 19287 Year 2018

Processing Hitter (307/496): ID 5221 Year 2018

Processing Hitter (308/496): ID 15947 Year 2018

Processing Hitter (309/496): ID 16448 Year 2018

Processing Hitter (310/496): ID 9787 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (311/496): ID 16725 Year 2018

Processing Hitter (312/496): ID 5503 Year 2018

Processing Hitter (313/496): ID 16246 Year 2018

Processing Hitter (314/496): ID 17075 Year 2018

Processing Hitter (315/496): ID 15407 Year 2018

Processing Hitter (316/496): ID 10123 Year 2018

Processing Hitter (317/496): ID 15873 Year 2018

Processing Hitter (318/496): ID 19990 Year 2018

Processing Hitter (319/496): ID 29573 Year 2025

Processing Hitter (320/496): ID 16953 Year 2025

--- Hitter checkpoint saved.

Processing Hitter (321/496): ID 27493 Year 2025

Processing Hitter (322/496): ID 15279 Year 2018

Processing Hitter (323/496): ID 14168 Year 2018

Processing Hitter (324/496): ID 16925 Year 2025

Processing Hitter (325/496): ID 3878 Year 2018

Processing Hitter (326/496): ID 3364 Year 2018

Processing Hitter (327/496): ID 10953 Year 2018

Processing Hitter (328/496): ID 9433 Year 2018

Processing Hitter (329/496): ID 13419 Year 2018

Processing Hitter (330/496): ID 13788 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (331/496): ID 1841 Year 2018

Processing Hitter (332/496): ID 8223 Year 2018

Processing Hitter (333/496): ID 9968 Year 2018

Processing Hitter (334/496): ID 16417 Year 2025

Processing Hitter (335/496): ID 21780 Year 2025

Processing Hitter (336/496): ID 22766 Year 2025

Processing Hitter (337/496): ID 29782 Year 2025

Processing Hitter (338/496): ID 18300 Year 2019

Processing Hitter (339/496): ID 11903 Year 2019

Processing Hitter (340/496): ID 8700 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (341/496): ID 10587 Year 2019

Processing Hitter (342/496): ID 5398 Year 2018

Processing Hitter (343/496): ID 15189 Year 2019

Processing Hitter (344/496): ID 15071 Year 2019

Processing Hitter (345/496): ID 17807 Year 2019

Processing Hitter (346/496): ID 18363 Year 2018

Processing Hitter (347/496): ID 15071 Year 2018

Processing Hitter (348/496): ID 14678 Year 2019

Processing Hitter (349/496): ID 14528 Year 2018

Processing Hitter (350/496): ID 6448 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (351/496): ID 17620 Year 2018

Processing Hitter (352/496): ID 15734 Year 2018

Processing Hitter (353/496): ID 13910 Year 2018

Processing Hitter (354/496): ID 16980 Year 2019

Processing Hitter (355/496): ID 3787 Year 2018

Processing Hitter (356/496): ID 5557 Year 2018

Processing Hitter (357/496): ID 4676 Year 2019

Processing Hitter (358/496): ID 11836 Year 2018

Processing Hitter (359/496): ID 14272 Year 2018

Processing Hitter (360/496): ID 10603 Year 2018

--- Hitter checkpoint saved.

Processing Hitter (361/496): ID 15467 Year 2018

Processing Hitter (362/496): ID 16981 Year 2018

Processing Hitter (363/496): ID 12399 Year 2018

Processing Hitter (364/496): ID 16980 Year 2018

Processing Hitter (365/496): ID 10767 Year 2018

Processing Hitter (366/496): ID 20023 Year 2019

Processing Hitter (367/496): ID 10322 Year 2020

Processing Hitter (368/496): ID 19151 Year 2020

Processing Hitter (369/496): ID 17710 Year 2020

Processing Hitter (370/496): ID 11863 Year 2020

--- Hitter checkpoint saved.

Processing Hitter (371/496): ID 19643 Year 2020

Processing Hitter (372/496): ID 9205 Year 2020

Processing Hitter (373/496): ID 11145 Year 2020

Processing Hitter (374/496): ID 25040 Year 2024

Processing Hitter (375/496): ID 25505 Year 2024

Processing Hitter (376/496): ID 11494 Year 2019

Processing Hitter (377/496): ID 17022 Year 2019

Processing Hitter (378/496): ID 19979 Year 2019

Processing Hitter (379/496): ID 16221 Year 2019

Processing Hitter (380/496): ID 11836 Year 2019

--- Hitter checkpoint saved.

Processing Hitter (381/496): ID 20100 Year 2019

Processing Hitter (382/496): ID 12808 Year 2019

Processing Hitter (383/496): ID 9077 Year 2020

Processing Hitter (384/496): ID 14387 Year 2020

Processing Hitter (385/496): ID 12950 Year 2020

Processing Hitter (386/496): ID 16285 Year 2020

Processing Hitter (387/496): ID 10030 Year 2020


# 2026 Hitter Run, same logic just for 2026 data.

In [26]:
# 1. SETUP RESUME LOGIC & 2026-SPECIFIC FILENAMES
checkpoint_hitter_2026 <- "hitter_logs_2026_checkpoint.rds"

if (file.exists(checkpoint_hitter_2026)) {
  hitter_logs_list_2026 <- readRDS(checkpoint_hitter_2026)
  
  # Identify which ID/Year combos we already have
  # Converting to character to avoid the double/character type mismatch error
  completed_hitters_2026 <- bind_rows(hitter_logs_list_2026) %>%
    distinct(BatterID, Year) %>%
    mutate(BatterID = as.character(BatterID))
  
  # Filter our 2026 queue
  queue_hitter_2026 <- unique_hitter_seasons_2026 %>%
    mutate(BatterID = as.character(BatterID)) %>%
    anti_join(completed_hitters_2026, by = c("BatterID", "Year"))
  
  message(paste("Resuming 2026 Hitter pull... skipping", nrow(completed_hitters_2026), "already processed."))
} else {
  hitter_logs_list_2026 <- list()
  queue_hitter_2026 <- unique_hitter_seasons_2026
}

# 2. THE LOOP
if(nrow(queue_hitter_2026) > 0) {
  for(i in 1:nrow(queue_hitter_2026)) {
    curr_b_id <- queue_hitter_2026$BatterID[i]
    curr_b_year <- queue_hitter_2026$Year[i]
    
    message(paste0("2026 Hitter Task (", i, "/", nrow(queue_hitter_2026), "): ID ", curr_b_id, " Year ", curr_b_year))
    
    # Try to fetch hitter logs from FanGraphs
    log_hitter_data <- tryCatch({
      fg_batter_game_logs(playerid = curr_b_id, year = curr_b_year)
    }, error = function(e) {
      if (grepl("403", e$message) || grepl("payload", e$message)) {
        message("!!! API Blocker detected. Cooling down for 120 seconds...")
        Sys.sleep(120) 
        return(NULL)
      }
      return(NULL)
    })
    
    # 3. DATA VALIDATION & STORAGE
    if(!is.null(log_hitter_data) && nrow(log_hitter_data) > 0) {
      log_hitter_data$BatterID <- curr_b_id
      log_hitter_data$Year <- curr_b_year
      hitter_logs_list_2026[[length(hitter_logs_list_2026) + 1]] <- log_hitter_data
    }
    
    # Checkpoint every 10 hitters
    if (i %% 10 == 0) {
      saveRDS(hitter_logs_list_2026, checkpoint_hitter_2026)
      message("--- 2026 Hitter checkpoint saved.")
    }
    
    # Random sleep to avoid rate limiting (slightly more conservative for hitters)
    Sys.sleep(runif(1, 2.0, 4.5))
  }
}

# 4. FINAL ASSEMBLY
hitter_logs_2026_final <- bind_rows(hitter_logs_list_2026)
saveRDS(hitter_logs_2026_final, "hitter_logs_2026_final.rds")
message("2026 Process Complete! File saved as hitter_logs_2026_final.rds")

2026 Hitter Task (1/929): ID 22266 Year 2026

2026 Hitter Task (2/929): ID 22275 Year 2026

2026 Hitter Task (3/929): ID 19913 Year 2026

2026 Hitter Task (4/929): ID 24703 Year 2026

2026-04-24 02:48:25.605648: Invalid arguments or no batter game logs data available!

2026 Hitter Task (5/929): ID 26151 Year 2026

2026 Hitter Task (6/929): ID 19608 Year 2026

2026 Hitter Task (7/929): ID 20536 Year 2026

2026-04-24 02:48:33.473598: Invalid arguments or no batter game logs data available!

2026 Hitter Task (8/929): ID 16947 Year 2026

2026 Hitter Task (9/929): ID 18551 Year 2026

2026-04-24 02:48:40.79313: Invalid arguments or no batter game logs data available!

2026 Hitter Task (10/929): ID 18568 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (11/929): ID 10815 Year 2026

2026-04-24 02:48:46.41686: Invalid arguments or no batter game logs data available!

2026 Hitter Task (12/929): ID 18036 Year 2026

2026 Hitter Task (13/929): ID 11493 Year 2026

2026 Hitter Task (14/929): ID 12161 Year 2026

2026 Hitter Task (15/929): ID 29490 Year 2026

2026 Hitter Task (16/929): ID 2136 Year 2026

2026-04-24 02:49:04.626193: Invalid arguments or no batter game logs data available!

2026 Hitter Task (17/929): ID 27506 Year 2026

2026-04-24 02:49:09.105489: Invalid arguments or no batter game logs data available!

2026 Hitter Task (18/929): ID 22217 Year 2026

2026 Hitter Task (19/929): ID 28806 Year 2026

2026-04-24 02:49:16.782192: Invalid arguments or no batter game logs data available!

2026 Hitter Task (20/929): ID 16472 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (21/929): ID 11442 Year 2026

2026 Hitter Task (22/929): ID 20503 Year 2026

2026 Hitter Task (23/929): ID 15986 Year 2026

2026 Hitter Task (24/929): ID 19921 Year 2026

2026 Hitter Task (25/929): ID 25493 Year 2026

2026 Hitter Task (26/929): ID 29622 Year 2026

2026 Hitter Task (27/929): ID 19455 Year 2026

2026 Hitter Task (28/929): ID 21523 Year 2026

2026 Hitter Task (29/929): ID 26668 Year 2026

2026 Hitter Task (30/929): ID 17988 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (31/929): ID 26323 Year 2026

2026 Hitter Task (32/929): ID 20321 Year 2026

2026-04-24 02:50:02.870964: Invalid arguments or no batter game logs data available!

2026 Hitter Task (33/929): ID 17982 Year 2026

2026 Hitter Task (34/929): ID 26517 Year 2026

2026 Hitter Task (35/929): ID 19522 Year 2026

2026 Hitter Task (36/929): ID 19997 Year 2026

2026 Hitter Task (37/929): ID 26208 Year 2026

2026-04-24 02:50:22.121609: Invalid arguments or no batter game logs data available!

2026 Hitter Task (38/929): ID 18126 Year 2026

2026-04-24 02:50:25.848717: Invalid arguments or no batter game logs data available!

2026 Hitter Task (39/929): ID 22515 Year 2026

2026 Hitter Task (40/929): ID 16376 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (41/929): ID 16505 Year 2026

2026 Hitter Task (42/929): ID 14854 Year 2026

2026 Hitter Task (43/929): ID 27478 Year 2026

2026 Hitter Task (44/929): ID 21871 Year 2026

2026 Hitter Task (45/929): ID 27735 Year 2026

2026-04-24 02:50:50.027567: Invalid arguments or no batter game logs data available!

2026 Hitter Task (46/929): ID 21558 Year 2026

2026 Hitter Task (47/929): ID 20054 Year 2026

2026-04-24 02:50:55.403577: Invalid arguments or no batter game logs data available!

2026 Hitter Task (48/929): ID 27899 Year 2026

2026 Hitter Task (49/929): ID 29606 Year 2026

2026-04-24 02:51:01.999273: Invalid arguments or no batter game logs data available!

2026 Hitter Task (50/929): ID 10681 Year 2026

2026-04-24 02:51:06.16763: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (51/929): ID 23800 Year 2026

2026 Hitter Task (52/929): ID 19392 Year 2026

2026 Hitter Task (53/929): ID 27464 Year 2026

2026 Hitter Task (54/929): ID 22168 Year 2026

2026-04-24 02:51:21.764568: Invalid arguments or no batter game logs data available!

2026 Hitter Task (55/929): ID 19296 Year 2026

2026 Hitter Task (56/929): ID 20391 Year 2026

2026 Hitter Task (57/929): ID 18400 Year 2026

2026-04-24 02:51:29.806997: Invalid arguments or no batter game logs data available!

2026 Hitter Task (58/929): ID 29518 Year 2026

2026 Hitter Task (59/929): ID 23691 Year 2026

2026 Hitter Task (60/929): ID 18395 Year 2026

2026-04-24 02:51:41.672036: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (61/929): ID 29931 Year 2026

2026 Hitter Task (62/929): ID 19864 Year 2026

2026-04-24 02:51:47.41852: Invalid arguments or no batter game logs data available!

2026 Hitter Task (63/929): ID 25979 Year 2026

2026 Hitter Task (64/929): ID 33189 Year 2026

2026 Hitter Task (65/929): ID 31347 Year 2026

2026 Hitter Task (66/929): ID 12434 Year 2026

2026-04-24 02:51:58.182146: Invalid arguments or no batter game logs data available!

2026 Hitter Task (67/929): ID 17548 Year 2026

2026 Hitter Task (68/929): ID 11615 Year 2026

2026-04-24 02:52:06.823487: Invalid arguments or no batter game logs data available!

2026 Hitter Task (69/929): ID 19956 Year 2026

2026 Hitter Task (70/929): ID 20220 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (71/929): ID 19318 Year 2026

2026-04-24 02:52:20.028754: Invalid arguments or no batter game logs data available!

2026 Hitter Task (72/929): ID 25353 Year 2026

2026-04-24 02:52:23.679151: Invalid arguments or no batter game logs data available!

2026 Hitter Task (73/929): ID 17338 Year 2026

2026 Hitter Task (74/929): ID 21501 Year 2026

2026 Hitter Task (75/929): ID 20437 Year 2026

2026 Hitter Task (76/929): ID 26466 Year 2026

2026 Hitter Task (77/929): ID 14161 Year 2026

2026 Hitter Task (78/929): ID 20538 Year 2026

2026-04-24 02:52:41.961191: Invalid arguments or no batter game logs data available!

2026 Hitter Task (79/929): ID 12144 Year 2026

2026-04-24 02:52:45.067765: Invalid arguments or no batter game logs data available!

2026 Hitter Task (80/929): ID 14813 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (81/929): ID 9774 Year 2026

2026 Hitter Task (82/929): ID 24610 Year 2026

2026 Hitter Task (83/929): ID 25660 Year 2026

2026 Hitter Task (84/929): ID 13510 Year 2026

2026 Hitter Task (85/929): ID 18839 Year 2026

2026 Hitter Task (86/929): ID 24934 Year 2026

2026 Hitter Task (87/929): ID 19950 Year 2026

2026 Hitter Task (88/929): ID 25180 Year 2026

2026 Hitter Task (89/929): ID 21865 Year 2026

2026 Hitter Task (90/929): ID 23690 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (91/929): ID 17027 Year 2026

2026-04-24 02:53:28.986921: Invalid arguments or no batter game logs data available!

2026 Hitter Task (92/929): ID 20123 Year 2026

2026 Hitter Task (93/929): ID 15640 Year 2026

2026 Hitter Task (94/929): ID 4949 Year 2026

2026 Hitter Task (95/929): ID 27562 Year 2026

2026 Hitter Task (96/929): ID 16997 Year 2026

2026 Hitter Task (97/929): ID 20454 Year 2026

2026 Hitter Task (98/929): ID 27647 Year 2026

2026-04-24 02:53:53.270593: Invalid arguments or no batter game logs data available!

2026 Hitter Task (99/929): ID 9874 Year 2026

2026-04-24 02:53:55.625195: Invalid arguments or no batter game logs data available!

2026 Hitter Task (100/929): ID 26396 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (101/929): ID 13624 Year 2026

2026 Hitter Task (102/929): ID 12533 Year 2026

2026 Hitter Task (103/929): ID 26299 Year 2026

2026 Hitter Task (104/929): ID 33333 Year 2026

2026 Hitter Task (105/929): ID 19566 Year 2026

2026 Hitter Task (106/929): ID 19287 Year 2026

2026 Hitter Task (107/929): ID 18900 Year 2026

2026 Hitter Task (108/929): ID 13620 Year 2026

2026 Hitter Task (109/929): ID 18363 Year 2026

2026 Hitter Task (110/929): ID 19290 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (111/929): ID 21534 Year 2026

2026 Hitter Task (112/929): ID 23697 Year 2026

2026 Hitter Task (113/929): ID 13152 Year 2026

2026 Hitter Task (114/929): ID 19354 Year 2026

2026 Hitter Task (115/929): ID 19734 Year 2026

2026-04-24 02:54:51.854292: Invalid arguments or no batter game logs data available!

2026 Hitter Task (116/929): ID 26438 Year 2026

2026 Hitter Task (117/929): ID 21009 Year 2026

2026 Hitter Task (118/929): ID 12916 Year 2026

2026 Hitter Task (119/929): ID 12927 Year 2026

2026 Hitter Task (120/929): ID 6184 Year 2026

2026-04-24 02:55:05.329796: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (121/929): ID 13590 Year 2026

2026-04-24 02:55:08.650161: Invalid arguments or no batter game logs data available!

2026 Hitter Task (122/929): ID 19251 Year 2026

2026 Hitter Task (123/929): ID 15362 Year 2026

2026 Hitter Task (124/929): ID 10231 Year 2026

2026-04-24 02:55:19.168292: Invalid arguments or no batter game logs data available!

2026 Hitter Task (125/929): ID 12160 Year 2026

2026-04-24 02:55:22.396506: Invalid arguments or no batter game logs data available!

2026 Hitter Task (126/929): ID 15905 Year 2026

2026 Hitter Task (127/929): ID 12856 Year 2026

2026 Hitter Task (128/929): ID 19918 Year 2026

2026 Hitter Task (129/929): ID 19611 Year 2026

2026 Hitter Task (130/929): ID 22581 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (131/929): ID 20352 Year 2026

2026 Hitter Task (132/929): ID 26477 Year 2026

2026 Hitter Task (133/929): ID 23565 Year 2026

2026 Hitter Task (134/929): ID 23782 Year 2026

2026 Hitter Task (135/929): ID 21682 Year 2026

2026-04-24 02:55:57.084332: Invalid arguments or no batter game logs data available!

2026 Hitter Task (136/929): ID 22542 Year 2026

2026 Hitter Task (137/929): ID 19627 Year 2026

2026 Hitter Task (138/929): ID 26368 Year 2026

2026-04-24 02:56:05.885588: Invalid arguments or no batter game logs data available!

2026 Hitter Task (139/929): ID 18171 Year 2026

2026-04-24 02:56:09.984742: Invalid arguments or no batter game logs data available!

2026 Hitter Task (140/929): ID 19844 Year 2026

2026-04-24 02:56:12.349179: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (141/929): ID 29766 Year 2026

2026 Hitter Task (142/929): ID 25575 Year 2026

2026-04-24 02:56:20.194589: Invalid arguments or no batter game logs data available!

2026 Hitter Task (143/929): ID 18353 Year 2026

2026-04-24 02:56:23.392849: Invalid arguments or no batter game logs data available!

2026 Hitter Task (144/929): ID 24488 Year 2026

2026-04-24 02:56:27.729474: Invalid arguments or no batter game logs data available!

2026 Hitter Task (145/929): ID 13621 Year 2026

2026 Hitter Task (146/929): ID 19260 Year 2026

2026 Hitter Task (147/929): ID 21853 Year 2026

2026 Hitter Task (148/929): ID 27479 Year 2026

2026 Hitter Task (149/929): ID 11609 Year 2026

2026 Hitter Task (150/929): ID 2967 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (151/929): ID 9777 Year 2026

2026 Hitter Task (152/929): ID 9218 Year 2026

2026 Hitter Task (153/929): ID 24679 Year 2026

2026 Hitter Task (154/929): ID 27475 Year 2026

2026 Hitter Task (155/929): ID 25782 Year 2026

2026 Hitter Task (156/929): ID 31349 Year 2026

2026 Hitter Task (157/929): ID 22186 Year 2026

2026 Hitter Task (158/929): ID 27555 Year 2026

2026 Hitter Task (159/929): ID 19755 Year 2026

2026 Hitter Task (160/929): ID 13611 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (161/929): ID 5361 Year 2026

2026 Hitter Task (162/929): ID 13066 Year 2026

2026 Hitter Task (163/929): ID 19955 Year 2026

2026-04-24 02:57:34.613207: Invalid arguments or no batter game logs data available!

2026 Hitter Task (164/929): ID 19197 Year 2026

2026 Hitter Task (165/929): ID 7802 Year 2026

2026 Hitter Task (166/929): ID 10472 Year 2026

2026-04-24 02:57:43.780469: Invalid arguments or no batter game logs data available!

2026 Hitter Task (167/929): ID 11038 Year 2026

2026-04-24 02:57:47.635445: Invalid arguments or no batter game logs data available!

2026 Hitter Task (168/929): ID 8623 Year 2026

2026-04-24 02:57:51.951941: Invalid arguments or no batter game logs data available!

2026 Hitter Task (169/929): ID 5517 Year 2026

2026 Hitter Task (170/929): ID 9847 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (171/929): ID 19326 Year 2026

2026 Hitter Task (172/929): ID 21711 Year 2026

2026 Hitter Task (173/929): ID 21524 Year 2026

2026 Hitter Task (174/929): ID 15679 Year 2026

2026-04-24 02:58:10.67514: Invalid arguments or no batter game logs data available!

2026 Hitter Task (175/929): ID 16512 Year 2026

2026 Hitter Task (176/929): ID 18577 Year 2026

2026 Hitter Task (177/929): ID 19600 Year 2026

2026-04-24 02:58:20.750652: Invalid arguments or no batter game logs data available!

2026 Hitter Task (178/929): ID 11489 Year 2026

2026-04-24 02:58:24.563528: Invalid arguments or no batter game logs data available!

2026 Hitter Task (179/929): ID 11445 Year 2026

2026-04-24 02:58:26.989346: Invalid arguments or no batter game logs data available!

2026 Hitter Task (180/929): ID 25616 Year 2026

2026-04-24 02:58:30.383178: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (181/929): ID 27577 Year 2026

2026 Hitter Task (182/929): ID 14221 Year 2026

2026 Hitter Task (183/929): ID 18360 Year 2026

2026 Hitter Task (184/929): ID 10324 Year 2026

2026 Hitter Task (185/929): ID 14344 Year 2026

2026 Hitter Task (186/929): ID 13185 Year 2026

2026-04-24 02:58:49.566263: Invalid arguments or no batter game logs data available!

2026 Hitter Task (187/929): ID 19352 Year 2026

2026-04-24 02:58:52.955927: Invalid arguments or no batter game logs data available!

2026 Hitter Task (188/929): ID 17128 Year 2026

2026 Hitter Task (189/929): ID 10950 Year 2026

2026-04-24 02:58:59.204159: Invalid arguments or no batter game logs data available!

2026 Hitter Task (190/929): ID 11281 Year 2026

2026-04-24 02:59:03.73201: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (191/929): ID 24729 Year 2026

2026 Hitter Task (192/929): ID 17838 Year 2026

2026-04-24 02:59:09.34262: Invalid arguments or no batter game logs data available!

2026 Hitter Task (193/929): ID 12861 Year 2026

2026-04-24 02:59:12.673275: Invalid arguments or no batter game logs data available!

2026 Hitter Task (194/929): ID 29634 Year 2026

2026-04-24 02:59:16.257268: Invalid arguments or no batter game logs data available!

2026 Hitter Task (195/929): ID 29630 Year 2026

2026 Hitter Task (196/929): ID 22766 Year 2026

2026-04-24 02:59:23.958579: Invalid arguments or no batter game logs data available!

2026 Hitter Task (197/929): ID 19339 Year 2026

2026-04-24 02:59:27.617337: Invalid arguments or no batter game logs data available!

2026 Hitter Task (198/929): ID 22896 Year 2026

2026 Hitter Task (199/929): ID 17901 Year 2026

2026 Hitter Task (200/929): ID 26197 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (201/929): ID 19901 Year 2026

2026 Hitter Task (202/929): ID 25543 Year 2026

2026-04-24 02:59:45.827405: Invalid arguments or no batter game logs data available!

2026 Hitter Task (203/929): ID 26149 Year 2026

2026-04-24 02:59:50.228189: Invalid arguments or no batter game logs data available!

2026 Hitter Task (204/929): ID 20311 Year 2026

2026-04-24 02:59:53.468928: Invalid arguments or no batter game logs data available!

2026 Hitter Task (205/929): ID 31394 Year 2026

2026-04-24 02:59:56.591265: Invalid arguments or no batter game logs data available!

2026 Hitter Task (206/929): ID 16939 Year 2026

2026 Hitter Task (207/929): ID 24257 Year 2026

2026-04-24 03:00:02.469393: Invalid arguments or no batter game logs data available!

2026 Hitter Task (208/929): ID 22532 Year 2026

2026 Hitter Task (209/929): ID 12976 Year 2026

2026 Hitter Task (210/929): ID 17919 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (211/929): ID 26319 Year 2026

2026 Hitter Task (212/929): ID 30116 Year 2026

2026 Hitter Task (213/929): ID 15998 Year 2026

2026 Hitter Task (214/929): ID 20036 Year 2026

2026 Hitter Task (215/929): ID 21479 Year 2026

2026 Hitter Task (216/929): ID 18314 Year 2026

2026 Hitter Task (217/929): ID 27769 Year 2026

2026 Hitter Task (218/929): ID 21693 Year 2026

2026 Hitter Task (219/929): ID 2396 Year 2026

2026 Hitter Task (220/929): ID 24618 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (221/929): ID 27462 Year 2026

2026 Hitter Task (222/929): ID 27684 Year 2026

2026 Hitter Task (223/929): ID 25764 Year 2026

2026 Hitter Task (224/929): ID 27676 Year 2026

2026 Hitter Task (225/929): ID 7304 Year 2026

2026 Hitter Task (226/929): ID 22197 Year 2026

2026 Hitter Task (227/929): ID 15464 Year 2026

2026-04-24 03:01:08.412223: Invalid arguments or no batter game logs data available!

2026 Hitter Task (228/929): ID 15223 Year 2026

2026 Hitter Task (229/929): ID 22715 Year 2026

2026 Hitter Task (230/929): ID 21614 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (231/929): ID 22799 Year 2026

2026 Hitter Task (232/929): ID 21622 Year 2026

2026 Hitter Task (233/929): ID 19238 Year 2026

2026 Hitter Task (234/929): ID 13145 Year 2026

2026 Hitter Task (235/929): ID 10243 Year 2026

2026 Hitter Task (236/929): ID 12552 Year 2026

2026 Hitter Task (237/929): ID 25878 Year 2026

2026 Hitter Task (238/929): ID 17696 Year 2026

2026-04-24 03:01:49.789699: Invalid arguments or no batter game logs data available!

2026 Hitter Task (239/929): ID 17040 Year 2026

2026-04-24 03:01:54.348782: Invalid arguments or no batter game logs data available!

2026 Hitter Task (240/929): ID 7859 Year 2026

2026-04-24 03:01:58.999253: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (241/929): ID 24064 Year 2026

2026 Hitter Task (242/929): ID 25479 Year 2026

2026 Hitter Task (243/929): ID 15112 Year 2026

2026 Hitter Task (244/929): ID 17907 Year 2026

2026-04-24 03:02:12.673411: Invalid arguments or no batter game logs data available!

2026 Hitter Task (245/929): ID 25845 Year 2026

2026-04-24 03:02:14.919765: Invalid arguments or no batter game logs data available!

2026 Hitter Task (246/929): ID 11680 Year 2026

2026 Hitter Task (247/929): ID 31431 Year 2026

2026 Hitter Task (248/929): ID 29715 Year 2026

2026 Hitter Task (249/929): ID 27615 Year 2026

2026 Hitter Task (250/929): ID 21454 Year 2026

2026-04-24 03:02:29.303654: Invalid arguments or no batter game logs data available!

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (251/929): ID 22263 Year 2026

2026 Hitter Task (252/929): ID 29949 Year 2026

2026-04-24 03:02:37.177424: Invalid arguments or no batter game logs data available!

2026 Hitter Task (253/929): ID 24816 Year 2026

2026 Hitter Task (254/929): ID 26121 Year 2026

2026 Hitter Task (255/929): ID 18030 Year 2026

2026 Hitter Task (256/929): ID 15878 Year 2026

2026 Hitter Task (257/929): ID 25816 Year 2026

2026 Hitter Task (258/929): ID 26224 Year 2026

2026 Hitter Task (259/929): ID 16478 Year 2026

2026 Hitter Task (260/929): ID 16252 Year 2026

--- 2026 Hitter checkpoint saved.

2026 Hitter Task (261/929): ID 11579 Year 2026

2026 Hitter Task (262/929): ID 21618 Year 2026

2026 Hitter Task (263/929): ID 26294 Year 2026

2026 Hitter Task (264/929): ID 11737 Year 2026

2026 Hitter Task (265/929): ID 11739 Year 2026

2026 Hitter Task (266/929): ID 20202 Year 2026

2026 Hitter Task (267/929): ID 24336 Year 2026

2026-04-24 03:03:28.980056: Invalid arguments or no batter game logs data available!

2026 Hitter Task (268/929): ID 23818 Year 2026

2026-04-24 03:03:33.537559: Invalid arguments or no batter game logs data available!

2026 Hitter Task (269/929): ID 7739 Year 2026

2026 Hitter Task (270/929): ID 19346 Year 2026

--- 2026 Hitter checkpoint saved.


In [12]:
write_csv(master_hitter_logs, "BatterGameLogFact.csv")

In [28]:
write_csv(hitter_logs_2026_final, "BatterGameLogFact2026.csv")

# Bullpen

In [111]:
# For each possible year and month, return pitcher data for bullpens

years <- c(2017,2018,2019,2020,2021,2022,2023,2024,2025)
months <- c(3,5,6,7,8,9)

results_list <- list()
counter <- 1

for (yr in years) {
  for (mon in months) {
    
    if (mon == 3){
        end_month <- 4
        first_day <- make_date(yr, mon, 1)
        first_day_following <- make_date(yr, end_month, 1)
        last_day  <- ceiling_date(first_day_following, "month") - days(1)
        month_table <- 4
    }
    else{
    first_day <- make_date(yr, mon, 1)
    last_day  <- ceiling_date(first_day, "month") - days(1)
    month_table <- mon
    }

    stats <- bref_daily_pitcher(t1 = as.character(first_day), t2 = as.character(last_day))

    if(!is.null(stats) && nrow(stats) > 0) {
      stats <- stats %>% mutate(query_year = yr, query_month = month_table)

      results_list[[counter]] <- stats
      counter <- counter + 1
    }

    Sys.sleep(3)

    #print(first_day)
    #print(last_day)
  }}

2026-04-12 16:29:31.03516: Invalid arguments or no daily pitcher data available!

2026-04-12 16:29:36.161138: Invalid arguments or no daily pitcher data available!

2026-04-12 16:29:41.247068: Invalid arguments or no daily pitcher data available!

In [118]:
# Filter down the pitching data into SP and RP

bref_monthly_pitching <- bind_rows(results_list)

bref_monthly_sp <- bref_monthly_pitching %>% filter(GS >= 1)
bref_monthly_rp <- bref_monthly_pitching %>% mutate(GS = as.numeric(GS), G = as.numeric(G)) %>% filter(GS == 0 | (GS < (G/2)))

In [120]:
write_csv(bref_monthly_sp, "bref_monthly_sp.csv")
write_csv(bref_monthly_rp, "bref_monthly_rp.csv")

# Fangraphs Pitching Fact

In [46]:
# Retrieve yearly FangGraphs pitching stats from 2015 to 2025

fg_pitching_fact15 <- fg_pitcher_leaders(startseason = 2015, endseason = 2015)
fg_pitching_fact16 <- fg_pitcher_leaders(startseason = 2016, endseason = 2016)
fg_pitching_fact17 <- fg_pitcher_leaders(startseason = 2017, endseason = 2017)
fg_pitching_fact18 <- fg_pitcher_leaders(startseason = 2018, endseason = 2018)
fg_pitching_fact19 <- fg_pitcher_leaders(startseason = 2019, endseason = 2019)
fg_pitching_fact20 <- fg_pitcher_leaders(startseason = 2020, endseason = 2020)
fg_pitching_fact21 <- fg_pitcher_leaders(startseason = 2021, endseason = 2021)
fg_pitching_fact22 <- fg_pitcher_leaders(startseason = 2022, endseason = 2022)
fg_pitching_fact23 <- fg_pitcher_leaders(startseason = 2023, endseason = 2023)
fg_pitching_fact24 <- fg_pitcher_leaders(startseason = 2024, endseason = 2024)
fg_pitching_fact25 <- fg_pitcher_leaders(startseason = 2025, endseason = 2025)

fg_pitching_fact <- bind_rows(fg_pitching_fact15,fg_pitching_fact16,fg_pitching_fact17,fg_pitching_fact18,fg_pitching_fact19,fg_pitching_fact20,fg_pitching_fact21,fg_pitching_fact22,fg_pitching_fact23,
fg_pitching_fact24,fg_pitching_fact25)

In [49]:
write_csv(fg_pitching_fact, "fg_pitching_fact.csv")

# Hitting

---------
---------
---------

In [162]:
# Retrieve yearly FangGraphs hitting stats from 2015 to 2025

fg_hitting_fact15 <- fg_batter_leaders(startseason = 2015, endseason = 2015)
fg_hitting_fact16 <- fg_batter_leaders(startseason = 2016, endseason = 2016)
fg_hitting_fact17 <- fg_batter_leaders(startseason = 2017, endseason = 2017)
fg_hitting_fact18 <- fg_batter_leaders(startseason = 2018, endseason = 2018)
fg_hitting_fact19 <- fg_batter_leaders(startseason = 2019, endseason = 2019)
fg_hitting_fact20 <- fg_batter_leaders(startseason = 2020, endseason = 2020)
fg_hitting_fact21 <- fg_batter_leaders(startseason = 2021, endseason = 2021)
fg_hitting_fact22 <- fg_batter_leaders(startseason = 2022, endseason = 2022)
fg_hitting_fact23 <- fg_batter_leaders(startseason = 2023, endseason = 2023)
fg_hitting_fact24 <- fg_batter_leaders(startseason = 2024, endseason = 2024)
fg_hitting_fact25 <- fg_batter_leaders(startseason = 2025, endseason = 2025)


fg_hitting_fact <- bind_rows(fg_hitting_fact15,fg_hitting_fact16,fg_hitting_fact17,fg_hitting_fact18,fg_hitting_fact19,fg_hitting_fact20,fg_hitting_fact21,fg_hitting_fact22,fg_hitting_fact23,
fg_hitting_fact24,fg_hitting_fact25)

In [164]:
write_csv(fg_hitting_fact, "fg_hitting_fact.csv")

## Box Score Information for 2026 Games (Used for Live Feature)

In [3]:
mlb_schedule_2026 <- mlb_schedule(season = 2026)

In [13]:
mlb_schedule_2026 <- mlb_schedule_2026 %>% filter(date < '2026-04-23') %>% filter(date >= '2026-03-25')

In [15]:
print(mlb_schedule_2026)

── MLB Schedule data from MLB.com ─────────────────────────── baseballr 1.6.0 ──

ℹ Data updated: 2026-04-24 04:22:14 CDT

# A tibble: 371 × 67
   date      total_items total_events total_games total_games_in_progr…¹ game_pk
   <chr>           <int>        <int>       <int>                  <int>   <int>
 1 2026-03-…           1            0           1                      0  823244
 2 2026-03-…          11            0          11                      0  823649
 3 2026-03-…          11            0          11                      0  823812
 4 2026-03-…          11            0          11                      0  824704
 5 2026-03-…          11            0          11                      0  824865
 6 2026-03-…          11            0          11                      0  824541
 7 2026-03-…          11            0          11                      0  824218
 8 2026-03-…          11            0          11                      0  823325
 9 2026-03-…          11            0          11                      0  823081
10 2026-03-…          11            0          11                      0  823486
# ℹ 361 more rows
# ℹ abbreviated name: ¹​total_games_in_progress
# ℹ 61 more variables: game_guid <chr>, link <chr>, game_type <chr>,
#   season <chr>, game_date <chr>, official_date <chr>, is_tie <lgl>,
#   game_number <int>, public_facing <lgl>, double_header <chr>,
#   gameday_type <chr>, tiebreaker <chr>, calendar_event_id <chr>,
#   season_display <chr>, day_night <chr>, scheduled_innings <int>, …

In [18]:
mlb_game_linescore(game_pk = 822745)

  game_pk home_team_id home_team_name       away_team_id away_team_name num
1 822745  120          Washington Nationals 144          Atlanta Braves 1
2 822745  120          Washington Nationals 144          Atlanta Braves 2
3 822745  120          Washington Nationals 144          Atlanta Braves 3
4 822745  120          Washington Nationals 144          Atlanta Braves 4
5 822745  120          Washington Nationals 144          Atlanta Braves 5
6 822745  120          Washington Nationals 144          Atlanta Braves 6
7 822745  120          Washington Nationals 144          Atlanta Braves 7
8 822745  120          Washington Nationals 144          Atlanta Braves 8
9 822745  120          Washington Nationals 144          Atlanta Braves 9
  ordinal_num home_runs home_hits home_errors ⋯
1 1st         1         1         0           ⋯
2 2nd         0         2         0           ⋯
3 3rd         0         0         0           ⋯
4 4th         1         2         0           ⋯
5 5th         0         0         0           ⋯
6 6th         0         0         0           ⋯
7 7th         0         0         0           ⋯
8 8th         0         0         0           ⋯
9 9th         0         0         0           ⋯
  away_team_record_league_record_losses away_team_record_league_record_ties
1 8                                     0
2 8                                     0
3 8                                     0
4 8                                     0
5 8                                     0
6 8                                     0
7 8                                     0
8 8                                     0
9 8                                     0
  away_team_record_league_record_pct away_team_record_division_leader
1 .692                               FALSE
2 .692                               FALSE
3 .692                               FALSE
4 .692                               FALSE
5 .692                               FALSE
6 .692                               FALSE
7 .692                               FALSE
8 .692                               FALSE
9 .692                               FALSE
  away_team_record_wins away_team_record_losses
1 18                    8
2 18                    8
3 18                    8
4 18                    8
5 18                    8
6 18                    8
7 18                    8
8 18                    8
9 18                    8
  away_team_record_winning_percentage away_team_franchise_name
1 .692                                Atlanta
2 .692                                Atlanta
3 .692                                Atlanta
4 .692                                Atlanta
5 .692                                Atlanta
6 .692                                Atlanta
7 .692                                Atlanta
8 .692                                Atlanta
9 .692                                Atlanta
  away_team_club_name away_team_active
1 Braves              TRUE
2 Braves              TRUE
3 Braves              TRUE
4 Braves              TRUE
5 Braves              TRUE
6 Braves              TRUE
7 Braves              TRUE
8 Braves              TRUE
9 Braves              TRUE

In [19]:
game_pks <- mlb_schedule_2026$game_pk

# 2. Initialize an empty tibble to hold the results
BoxScores26 <- tibble()

# 3. The Loop
for (i in seq_along(game_pks)) {
  current_pk <- game_pks[i]
  
  message(paste0("Fetching Box Score (", i, "/", length(game_pks), "): ", current_pk))
  
  # Fetch linescore and handle errors
  linescore_raw <- tryCatch({
    mlb_game_linescore(game_pk = current_pk)
  }, error = function(e) {
    message(paste("Error fetching game", current_pk, ":", e$message))
    return(NULL)
  })
  
  # 4. Condense the Inning-by-Inning data to a Game Summary
  if (!is.null(linescore_raw) && nrow(linescore_raw) > 0) {
    
    game_summary <- linescore_raw %>%
      summarize(
        game_pk = current_pk,
        away_team_name = first(away_team_name),
        home_team_name = first(home_team_name),
        away_runs_total = sum(away_runs, na.rm = TRUE),
        home_runs_total = sum(home_runs, na.rm = TRUE)
      )
    
    BoxScores26 <- bind_rows(BoxScores26, game_summary)
  }
  
  Sys.sleep(0.5)
}

Fetching Box Score (1/371): 823244

Fetching Box Score (2/371): 823649

Fetching Box Score (3/371): 823812

Fetching Box Score (4/371): 824704

Fetching Box Score (5/371): 824865

Fetching Box Score (6/371): 824541

Fetching Box Score (7/371): 824218

Fetching Box Score (8/371): 823325

Fetching Box Score (9/371): 823081

Fetching Box Score (10/371): 823486

Fetching Box Score (11/371): 823974

Fetching Box Score (12/371): 823163

Fetching Box Score (13/371): 823243

Fetching Box Score (14/371): 822839

Fetching Box Score (15/371): 823893

Fetching Box Score (16/371): 824946

Fetching Box Score (17/371): 824216

Fetching Box Score (18/371): 823324

Fetching Box Score (19/371): 823162

Fetching Box Score (20/371): 823971

Fetching Box Score (21/371): 823082

Fetching Box Score (22/371): 824701

Fetching Box Score (23/371): 822838

Fetching Box Score (24/371): 824862

Fetching Box Score (25/371): 823488

Fetching Box Score (26/371): 824540

Fetching Box Score (27/371): 823651

Fetching Box Score (28/371): 823892

Fetching Box Score (29/371): 824213

Fetching Box Score (30/371): 823811

Fetching Box Score (31/371): 824945

Fetching Box Score (32/371): 823241

Fetching Box Score (33/371): 823323

Fetching Box Score (34/371): 823973

Fetching Box Score (35/371): 823161

Fetching Box Score (36/371): 824864

Fetching Box Score (37/371): 823487

Fetching Box Score (38/371): 824944

Fetching Box Score (39/371): 822837

Fetching Box Score (40/371): 824538

Fetching Box Score (41/371): 823647

Fetching Box Score (42/371): 823891

Fetching Box Score (43/371): 824215

Fetching Box Score (44/371): 823810

Fetching Box Score (45/371): 823079

Fetching Box Score (46/371): 824700

Fetching Box Score (47/371): 823160

Fetching Box Score (48/371): 824135

Fetching Box Score (49/371): 824863

Fetching Box Score (50/371): 824539

Fetching Box Score (51/371): 823484

Fetching Box Score (52/371): 823890

Fetching Box Score (53/371): 822834

Fetching Box Score (54/371): 824943

Fetching Box Score (55/371): 824702

Fetching Box Score (56/371): 823809

Fetching Box Score (57/371): 823080

Fetching Box Score (58/371): 824214

Fetching Box Score (59/371): 823320

Fetching Box Score (60/371): 823159

Fetching Box Score (61/371): 825108

Fetching Box Score (62/371): 823972

Fetching Box Score (63/371): 824861

Fetching Box Score (64/371): 824537

Fetching Box Score (65/371): 823485

Fetching Box Score (66/371): 823888

Fetching Box Score (67/371): 822836

Fetching Box Score (68/371): 824942

Fetching Box Score (69/371): 824699

Fetching Box Score (70/371): 823807

Fetching Box Score (71/371): 823077

Fetching Box Score (72/371): 824212

Fetching Box Score (73/371): 825107

Fetching Box Score (74/371): 823322

Fetching Box Score (75/371): 823158

Fetching Box Score (76/371): 823969

Fetching Box Score (77/371): 824940

Fetching Box Score (78/371): 824860

Fetching Box Score (79/371): 824536

Fetching Box Score (80/371): 823483

Fetching Box Score (81/371): 822835

Fetching Box Score (82/371): 823889

Fetching Box Score (83/371): 823078

Fetching Box Score (84/371): 823806

Fetching Box Score (85/371): 824211

Fetching Box Score (86/371): 824698

Fetching Box Score (87/371): 825106

Fetching Box Score (88/371): 823321

Fetching Box Score (89/371): 823157

Fetching Box Score (90/371): 824136

Fetching Box Score (91/371): 823970

Fetching Box Score (92/371): 824133

Fetching Box Score (93/371): 825105

Fetching Box Score (94/371): 823242

Fetching Box Score (95/371): 824621

Fetching Box Score (96/371): 822758

Fetching Box Score (97/371): 824299

Fetching Box Score (98/371): 823568

Fetching Box Score (99/371): 824786

Fetching Box Score (100/371): 824621

Fetching Box Score (101/371): 822919

Fetching Box Score (102/371): 824458

Fetching Box Score (103/371): 823732

Fetching Box Score (104/371): 824377

Fetching Box Score (105/371): 823406

Fetching Box Score (106/371): 824056

Fetching Box Score (107/371): 825026

Fetching Box Score (108/371): 825103

Fetching Box Score (109/371): 823240

Fetching Box Score (110/371): 824134

Fetching Box Score (111/371): 824295

Fetching Box Score (112/371): 824622

Fetching Box Score (113/371): 824132

Fetching Box Score (114/371): 824134

Fetching Box Score (115/371): 822757

Fetching Box Score (116/371): 825027

Fetching Box Score (117/371): 823404

Fetching Box Score (118/371): 824782

Fetching Box Score (119/371): 822920

Fetching Box Score (120/371): 823569

Fetching Box Score (121/371): 823730

Fetching Box Score (122/371): 825104

Fetching Box Score (123/371): 824378

Fetching Box Score (124/371): 823239

Fetching Box Score (125/371): 824054

Fetching Box Score (126/371): 824460

Fetching Box Score (127/371): 824459

Fetching Box Score (128/371): 824460

Fetching Box Score (129/371): 822756

Fetching Box Score (130/371): 823405

Fetching Box Score (131/371): 824781

Fetching Box Score (132/371): 823566

Fetching Box Score (133/371): 823729

Fetching Box Score (134/371): 824620

Fetching Box Score (135/371): 824131

Fetching Box Score (136/371): 822917

Fetching Box Score (137/371): 824379

Fetching Box Score (138/371): 825025

Fetching Box Score (139/371): 823238

Fetching Box Score (140/371): 824053

Fetching Box Score (141/371): 825102

Fetching Box Score (142/371): 824296

Fetching Box Score (143/371): 823002

Fetching Box Score (144/371): 824456

Fetching Box Score (145/371): 823401

Fetching Box Score (146/371): 823886

Fetching Box Score (147/371): 822755

Fetching Box Score (148/371): 824783

Fetching Box Score (149/371): 822832

Fetching Box Score (150/371): 823728

Fetching Box Score (151/371): 824619

Fetching Box Score (152/371): 822918

Fetching Box Score (153/371): 824376

Fetching Box Score (154/371): 824052

Fetching Box Score (155/371): 823237

Fetching Box Score (156/371): 824457

Fetching Box Score (157/371): 824618

Fetching Box Score (158/371): 823648

Fetching Box Score (159/371): 823402

Fetching Box Score (160/371): 822999

Fetching Box Score (161/371): 823887

Fetching Box Score (162/371): 822754

Fetching Box Score (163/371): 824780

Fetching Box Score (164/371): 823567

Fetching Box Score (165/371): 822831

Fetching Box Score (166/371): 823727

Fetching Box Score (167/371): 822916

Fetching Box Score (168/371): 824375

Fetching Box Score (169/371): 824051

Fetching Box Score (170/371): 823235

Fetching Box Score (171/371): 823403

Fetching Box Score (172/371): 824455

Fetching Box Score (173/371): 824779

Fetching Box Score (174/371): 824617

Fetching Box Score (175/371): 822915

Fetching Box Score (176/371): 822833

Fetching Box Score (177/371): 824374

Fetching Box Score (178/371): 823234

Fetching Box Score (179/371): 822753

Fetching Box Score (180/371): 824050

Fetching Box Score (181/371): 823646

Fetching Box Score (182/371): 823000

Fetching Box Score (183/371): 823885

Fetching Box Score (184/371): 823564

Fetching Box Score (185/371): 823726

Fetching Box Score (186/371): 823884

Fetching Box Score (187/371): 823565

Fetching Box Score (188/371): 823724

Fetching Box Score (189/371): 823645

Fetching Box Score (190/371): 824130

Fetching Box Score (191/371): 823319

Fetching Box Score (192/371): 824695

Fetching Box Score (193/371): 823482

Fetching Box Score (194/371): 824297

Fetching Box Score (195/371): 824534

Fetching Box Score (196/371): 822829

Fetching Box Score (197/371): 823643

Fetching Box Score (198/371): 822997

Fetching Box Score (199/371): 824858

Fetching Box Score (200/371): 824941

Fetching Box Score (201/371): 824128

Fetching Box Score (202/371): 823808

Fetching Box Score (203/371): 823076

Fetching Box Score (204/371): 823318

Fetching Box Score (205/371): 823156

Fetching Box Score (206/371): 823968

Fetching Box Score (207/371): 823480

Fetching Box Score (208/371): 824294

Fetching Box Score (209/371): 824697

Fetching Box Score (210/371): 822830

Fetching Box Score (211/371): 824535

Fetching Box Score (212/371): 823644

Fetching Box Score (213/371): 824129

Fetching Box Score (214/371): 822996

Fetching Box Score (215/371): 823805

Fetching Box Score (216/371): 824857

Fetching Box Score (217/371): 823074

Fetching Box Score (218/371): 824939

Fetching Box Score (219/371): 823316

Fetching Box Score (220/371): 823967

Fetching Box Score (221/371): 823155

Fetching Box Score (222/371): 824859

Fetching Box Score (223/371): 823479

Fetching Box Score (224/371): 822828

Fetching Box Score (225/371): 824533

Fetching Box Score (226/371): 823642

Fetching Box Score (227/371): 824293

Fetching Box Score (228/371): 822998

Fetching Box Score (229/371): 824126

Fetching Box Score (230/371): 823804

Fetching Box Score (231/371): 823075

Fetching Box Score (232/371): 824696

Fetching Box Score (233/371): 823317

Fetching Box Score (234/371): 823154

Fetching Box Score (235/371): 823966

Fetching Box Score (236/371): 824938

Fetching Box Score (237/371): 823153

Fetching Box Score (238/371): 824856

Fetching Box Score (239/371): 823400

Fetching Box Score (240/371): 823481

Fetching Box Score (241/371): 823563

Fetching Box Score (242/371): 824937

Fetching Box Score (243/371): 823725

Fetching Box Score (244/371): 823073

Fetching Box Score (245/371): 825024

Fetching Box Score (246/371): 823964

Fetching Box Score (247/371): 824853

Fetching Box Score (248/371): 824292

Fetching Box Score (249/371): 823398

Fetching Box Score (250/371): 824531

Fetching Box Score (251/371): 823478

Fetching Box Score (252/371): 823562

Fetching Box Score (253/371): 824935

Fetching Box Score (254/371): 823723

Fetching Box Score (255/371): 824616

Fetching Box Score (256/371): 823802

Fetching Box Score (257/371): 823072

Fetching Box Score (258/371): 824210

Fetching Box Score (259/371): 823315

Fetching Box Score (260/371): 825022

Fetching Box Score (261/371): 823965

Fetching Box Score (262/371): 824855

Fetching Box Score (263/371): 823071

Fetching Box Score (264/371): 823722

Fetching Box Score (265/371): 824291

Fetching Box Score (266/371): 823399

Fetching Box Score (267/371): 824532

Fetching Box Score (268/371): 823477

Fetching Box Score (269/371): 823561

Fetching Box Score (270/371): 824936

Fetching Box Score (271/371): 824615

Fetching Box Score (272/371): 823803

Fetching Box Score (273/371): 824209

Fetching Box Score (274/371): 823314

Fetching Box Score (275/371): 825021

Fetching Box Score (276/371): 823963

Fetching Box Score (277/371): 823396

Fetching Box Score (278/371): 824530

Fetching Box Score (279/371): 824289

Fetching Box Score (280/371): 823560

Fetching Box Score (281/371): 823801

Fetching Box Score (282/371): 824614

Fetching Box Score (283/371): 825023

Fetching Box Score (284/371): 824453

Fetching Box Score (285/371): 824208

Fetching Box Score (286/371): 823313

Fetching Box Score (287/371): 824693

Fetching Box Score (288/371): 824454

Fetching Box Score (289/371): 823476

Fetching Box Score (290/371): 822752

Fetching Box Score (291/371): 823397

Fetching Box Score (292/371): 823559

Fetching Box Score (293/371): 823883

Fetching Box Score (294/371): 824778

Fetching Box Score (295/371): 824207

Fetching Box Score (296/371): 823720

Fetching Box Score (297/371): 824373

Fetching Box Score (298/371): 824048

Fetching Box Score (299/371): 823152

Fetching Box Score (300/371): 825101

Fetching Box Score (301/371): 825019

Fetching Box Score (302/371): 823558

Fetching Box Score (303/371): 823721

Fetching Box Score (304/371): 824694

Fetching Box Score (305/371): 823394

Fetching Box Score (306/371): 822751

Fetching Box Score (307/371): 825020

Fetching Box Score (308/371): 824775

Fetching Box Score (309/371): 823882

Fetching Box Score (310/371): 824451

Fetching Box Score (311/371): 824206

Fetching Box Score (312/371): 823151

Fetching Box Score (313/371): 823474

Fetching Box Score (314/371): 824372

Fetching Box Score (315/371): 825098

Fetching Box Score (316/371): 824049

Fetching Box Score (317/371): 822750

Fetching Box Score (318/371): 823393

Fetching Box Score (319/371): 823556

Fetching Box Score (320/371): 824452

Fetching Box Score (321/371): 823881

Fetching Box Score (322/371): 824205

Fetching Box Score (323/371): 823718

Fetching Box Score (324/371): 824691

Fetching Box Score (325/371): 824371

Fetching Box Score (326/371): 825018

Fetching Box Score (327/371): 824047

Fetching Box Score (328/371): 823150

Fetching Box Score (329/371): 825100

Fetching Box Score (330/371): 824777

Fetching Box Score (331/371): 823475

Fetching Box Score (332/371): 824776

Fetching Box Score (333/371): 824450

Fetching Box Score (334/371): 822994

Fetching Box Score (335/371): 823879

Fetching Box Score (336/371): 822749

Fetching Box Score (337/371): 824125

Fetching Box Score (338/371): 824692

Fetching Box Score (339/371): 824370

Fetching Box Score (340/371): 824046

Fetching Box Score (341/371): 823149

Fetching Box Score (342/371): 824448

Fetching Box Score (343/371): 822995

Fetching Box Score (344/371): 823880

Fetching Box Score (345/371): 824290

Fetching Box Score (346/371): 822747

Fetching Box Score (347/371): 824773

Fetching Box Score (348/371): 823640

Fetching Box Score (349/371): 824127

Fetching Box Score (350/371): 824690

Fetching Box Score (351/371): 822914

Fetching Box Score (352/371): 824369

Fetching Box Score (353/371): 824045

Fetching Box Score (354/371): 823148

Fetching Box Score (355/371): 825099

Fetching Box Score (356/371): 823236

Fetching Box Score (357/371): 823878

Fetching Box Score (358/371): 824449

Fetching Box Score (359/371): 822993

Fetching Box Score (360/371): 824123

Fetching Box Score (361/371): 824044

Fetching Box Score (362/371): 823147

Fetching Box Score (363/371): 824286

Fetching Box Score (364/371): 822748

Fetching Box Score (365/371): 824774

Fetching Box Score (366/371): 823641

Fetching Box Score (367/371): 824688

Fetching Box Score (368/371): 822913

Fetching Box Score (369/371): 824367

Fetching Box Score (370/371): 825097

Fetching Box Score (371/371): 823231

In [20]:
# 1. Ensure the key column types match (both should be numeric)
BoxScores26 <- BoxScores26 %>%
  mutate(game_pk = as.numeric(game_pk))

mlb_schedule_2026 <- mlb_schedule_2026 %>%
  mutate(game_pk = as.numeric(game_pk))

# 2. Join to get the date and other relevant schedule info
BoxScores26_Final <- BoxScores26 %>%
  left_join(
    mlb_schedule_2026 %>% select(game_pk, date), 
    by = "game_pk"
  )

# 3. Clean up the date format if necessary
BoxScores26_Final <- BoxScores26_Final %>%
  mutate(date = as.Date(date))

# Verification
print(head(BoxScores26_Final))

Warning message in left_join(., mlb_schedule_2026 %>% select(game_pk, date), by = "game_pk"):
“Detected an unexpected many-to-many relationship between `x` and `y`.
ℹ Row 95 of `x` matches multiple rows in `y`.
ℹ Row 95 of `y` matches multiple rows in `x`.
ℹ If a many-to-many relationship is expected, set `relationship =
  "many-to-many"` to silence this warning.”

# A tibble: 6 × 6
  game_pk away_team_name       home_team_name    away_runs_total home_runs_total
    <dbl> <chr>                <chr>                       <int>           <int>
1  823244 New York Yankees     San Francisco Gi…               7               0
2  823649 Pittsburgh Pirates   New York Mets                   7              11
3  823812 Chicago White Sox    Milwaukee Brewers               2              14
4  824704 Washington Nationals Chicago Cubs                   10               4
5  824865 Minnesota Twins      Baltimore Orioles               1               2
6  824541 Boston Red Sox       Cincinnati Reds                 3               0
# ℹ 1 more variable: date <date>

In [21]:
write_csv(BoxScores26_Final, "BoxScores26_Final.csv")